### ISSUE TITLE
Need translators for app localization

### ISSUE THREAD

**Issue by ashutoshgngwr** [ashutoshgngwr/noice#108]
Please help in translating Noice to your local language.

**Note**: _Even if translations for your local language exist in Noice, it is a good idea to revisit them. The project is always under development and translations are lagging behind. If you have Android Studio environment setup on your local machine, clone the repository and take a look at `values/strings.xml`. Android Lint will highlight missing translations._

## Steps to translate

- Creating a new `strings.xml` file for translations
   1. Open the new file wizard under **File > New > Android resource file** in the Android Studio
   1. From `Available qualifiers` add `Locale` to `Chosen qualifiers`
   1. Select the correct language and region and create the new `strings.xml` file.
- Translate all the `translatable` strings in `values/strings.xml`
- _[Bonus]_ Translate the F-Droid/Play Store [metadata](https://github.com/ashutoshgngwr/noice/tree/master/fastlane/metadata/android). See [docs](https://docs.fastlane.tools/actions/supply/#images-and-screenshots).
- Create a new Pull Request
- _[Optional]_ Add your name to the Credits section in [AboutFragment](https://github.com/ashutoshgngwr/noice/blob/master/app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt). See [example](https://github.com/ashutoshgngwr/noice/blob/2e9e310bfe3e04cde6c0087b3d3bb733f86cae25/app/src/main/java/com/github/ashutoshgngwr/noice/fragment/AboutFragment.kt#L66-L70).

Also, see [CONTRIBUTING.md](https://github.com/ashutoshgngwr/noice/blob/master/CONTRIBUTING.md).

## Speeding up the process

You can use Google translate to quickly come up with rough translations of all the strings. But since additional context is needed to translate English to most languages properly, you should edit these rough translations by hand until it conveys same message as its English counterpart.

**Comment by Enchufadoo** [comment]
Hi, would like to translate to spanish (Latin america) if you want.

**Comment by ashutoshgngwr** [comment]
@Enchufadoo Please go ahead! Thanks for your contribution. :)

**Comment by yamaks2306** [comment]
Hey! If you don't mind, I'd like to help with the Russian translation.

**Comment by ashutoshgngwr** [comment]
@yamaks2306 please go ahead. Thank you for the contributions.

**Comment by CL** [comment]
I would like to contribute with the Brazilian Portuguese (pt-br) translation

**Comment by ashutoshgngwr** [comment]
@chagretes Please go ahead. Thank you for the contribution.

**Comment by CebolaBros64** [comment]
> I would like to contribute with the Brazilian Portuguese (pt-br) translation

How far ahead are you on your translation? I have a brazillian portuguese translation in progress as well

**Comment by ashutoshgngwr** [comment]
> > I would like to contribute with the Brazilian Portuguese (pt-br) translation
> 
> @chagretes How far ahead are you on your translation? I have a brazillian portuguese translation in progress as well

@CebolaBros64 I was starting to think that maintaining this issue is a waste of time. :sweat_smile:

**Comment by chagretes** [comment]
> > I would like to contribute with the Brazilian Portuguese (pt-br) translation
> 
> @chagretes How far ahead are you on your translation? I have a brazillian portuguese translation in progress as well

I still need to translate the metadata + screenshots.

**Comment by CebolaBros64** [comment]
Sure thing, then! I'll be making a pull request soon enough

**Comment by julianrrr** [comment]
Hi, I would like translate the app to spanish (es-ES)... As soon as possible I will create the PR

**Comment by ashutoshgngwr** [comment]
@julianrrr Can you please translate from 0.7.x branch. There are some strings related changes that aren't in the master yet.

**Comment by julianrrr** [comment]
> @julianrrr Can you please translate from 0.7.x branch? There are some strings related changes that aren't in the master yet.

Sure, no problem.

**Comment by patogit** [comment]
Maybe translatewiki.net would be useful?

**Comment by swedneck** [comment]
Perhaps it would be possible to use https://weblate.org to make translating easier?

**Comment by ashutoshgngwr** [comment]
@patogit @swedneck Created a [GitHub action](https://github.com/ashutoshgngwr/android-missing-translations) to keep track of missing translations. Will integrate it soon. (:

Also looking to do something about the outdated translations, not sure.

**Comment by patogit** [comment]
https://translatewiki.net takes care of all that sort of translation handling, finding outdated bits, exposes the project to a large community of translators, and costs nothing (donations surely appreciated). But sometimes solving problems in a new way is more fun :) and maybe you'll create new tools along the way.

**Comment by ashutoshgngwr** [comment]
@patogit You got that right! :sweat_smile:. The other thing is I want to minimize my context switch from GitHub.

**Comment by ashutoshgngwr** [comment]
Closing this in favor of #200.
