### ISSUE TITLE
crash when viewing Saved Presets after upgrading 0.2.7 -> 0.3.x

### ISSUE THREAD

**Issue by refola** [ashutoshgngwr/noice#110]
### Describe the bug
Noice crashes when I select "saved presets" after updating from version 0.2.7.

### To Reproduce
1. Downgrade to version 0.2.7 and reset Noice's app data.
2. Start a track and save as a preset.
3. Upgrade to version 0.3.x (tested with 0.3.1 and 0.3.3 on F-Droid).
4. Go to "Saved Presets".
5. Watch Noice crash immediately.

### Expected behavior
I expected my saved presets to be saved and accessible after updating Noice.

### Others
 - Device: OnePlus One
 - Android Version: Pie (Android 9.0, LineageOS 16.0, built on 2020-03-19.)
- App version: F-Droid

### Suspected cause: presets JSON format changes
Using the "Preferences Manager" app from F-Droid, I found a JSON-encoded "presets" setting. The schema seems to have changed between versions, as illustrated by these examples:
- Noice 0.2.7 "presets": `[{"a":"foo","b":[{"a":"birds","b":0.2,"c":60}]}]`
- Noice 0.3.1 "presets": `[{"a":"foo","b":[{"b":4,"c":30,"e":"birds"}]}]`

Note that I couldn't get this for Noice 0.3.3 because it crashes when I try to save a preset. I reset app data before each of theses tests to avoid conflicts. Noice 0.3.3 additionally crashes when trying to view saved presets from 0.3.1 (in addition to the crash when trying to view presets from 0.2.7), but not when viewing an empty list of presets.

I suspect that you'll want to change this bug to be more specifically about the JSON handling (which you seem to be aware of issues with due to PR #105) or split the different crash scenarios into different bugs. But this 0.2.7 -> 0.3.x upgrade crash is the one I personally ran into as a user.

**Comment by crogonint** [comment]
I can verify the behavior, haven't looked at the code.

**Comment by ashutoshgngwr** [comment]
Thanks for bringing the issue in notice. I now realise that I've screwed up big time. Its gonna be hard to both preserve presets saved on 0.2.7 and fix this issue at the same time. I'll try to come up with a solution that works in both cases. :)

**Comment by crogonint** [comment]
Personally, I already had to delete my presets, and I've temporarily downgraded back to 2.7. I don't mind of the presets get lost, this once. Maybe add a feature to back them up?

**Comment by ashutoshgngwr** [comment]
@crogonint I think Google backs up the app preferences by default. That is why I didn't take backups under consideration. I'll fix this ASAP.

**Comment by ashutoshgngwr** [comment]
@refola These are not multiple issues but one. In #105 , I only addressed half the concern that I thought was breaking backward compatibility. The second half of the issue is Proguard obfuscation.

**Comment by ashutoshgngwr** [comment]
@refola @crogonint Created #117 with the fix. Will merge it after testing it for a while.
