### ISSUE TITLE
Sounds not moving to the top of the list

### ISSUE THREAD

**Issue by crogonint** [ashutoshgngwr/noice#111]
Starting in version 0.3.1, sounds do not automatically move to the top of the list when enabled.

Not sure if this feature is necessary, but I noticed it.

Edit:
...not sure why there's no 'bug' tag on this.

**Comment by ashutoshgngwr** [comment]
I removed the feature in 0.3.0. a lot of changes happened recently with frequent releases so might have missed to mention it. :)

I'll close since this is intentional change.

**Comment by crogonint** [comment]
I note that if I come here by clicking the report issues button, when I return to the app, all of the enabled sounds are at the top of the list.

Is this behavior expected?
