### ISSUE TITLE
Sounds turn off

### ISSUE THREAD

**Issue by crogonint** [ashutoshgngwr/noice#112]
### Describe the bug
Starting in 0.3.1, at some point during the night, the sounds turn off. I suspect that they pause for a notification noise or something, then never turn back on.

### To Reproduce
1. Turn on some sounds.
2. When you wake up, they're off.
3. Double clicking one sound turns them all back on.

### Expected behavior
Sounds remain on until you shut them off (since there is no timer).

**Comment by crogonint** [comment]
APPEARS to be fixed in 3.4. I.note that notification sounds share the sound device with Noice now, instead of interrupting it.

I'll let you know tiptoe of

**Comment by crogonint** [comment]
I jumped the gun. Exact same issue this morning. I can't hear the sounds, even though they're still 'on' in the app. If I turn a sound off and back on, the audio turns back on.

**Comment by crogonint** [comment]
I think the volume is lowering over time. Every once in a while the volume... well, it wobbles around like someone is playing with the volume knob on a radio.

I had two repeatable effects happen this morning. I got a phone call before my alarm went off. Both the phone call and the alarm killed the volume of Noice, and didn't turn it back on. After the event, Noice remains muted. All of the individual sounds appear to be playing. I can click on/off for any one sound, and that sound appears to turn off, while the volumes of all of the other songs are instantly unmuted. Then I can click to turn the individual sound back on.

**Comment by crogonint** [comment]
Ok, now I can't repeat it. More the sounds continue under the alarm going off, and they don't mute at all when the alarm goes off.

I think some event must be happening while the app is playing all night.

**Comment by ashutoshgngwr** [comment]
@crogonint Thanks for the details. I'll look into this.

**Comment by crogonint** [comment]
Happened again this morning. I was pleased to hear the sounds were still playing when I woke up, then after I got a phone call, they stayed off.

Say, I wonder if the mute function in Noice is timing out during extended operations.. Like me sleeping through my alarm. 🤣

**Comment by ashutoshgngwr** [comment]
@crogonint I missed this earlier. There may be two reasons for this.

1. Your alarm takes audio focus and Noice pauses itself. In this case the notification should show a resume button.
2. The device CPU goes to sleep because Noice doesn't hold wake locks. This was by design.

The former case is a design recommendation from Google to avoid clutter in audio playback by multiple apps. The latter should be solved in 0.8.x where introducing Google Cast forces us to device wake locks.

**Comment by crogonint** [comment]
That's amazing. So how does it keep the device awake all night if it's not
using a wake lock? They really SHOULD have a low power setting which leaves
the audio channel and etc. open. One of the main uses for these devices is
as a music / mp3 player.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by ashutoshgngwr** [comment]
@crogonint The [documentation](https://developer.android.com/topic/performance/vitals/wakelock#best_practices) isn't clear on that. It is suggested that music players are required to acquire wake lock but Noice has been working fine until now (at least for me). I experimented with a few hours of continuous playback in earlier versions and it seemed to work without a hitch.

**Comment by crogonint** [comment]
Interesting

**Comment by crogonint** [comment]
_Not even gonna try to explain_

Lol!
