### ISSUE TITLE
Volume controls interlinked

### ISSUE THREAD

**Issue by crogonint** [ashutoshgngwr/noice#113]
### Describe the bug
Starting on 0.3.1 can't recall exactly which sound pair I noticed the behavior in, but for example, if the bonfire noise is on, and you turn the wind in tree nice on and raise its volume, the bonfire volume also goes up.

**Comment by ashutoshgngwr** [comment]
@crogonint I just tried to reproduce this on my end and with no luck. Please add device info (Memory, Android version, etc.) and a gif/video of the issue (if possible).

**Comment by crogonint** [comment]
Same device from before, it's a Motorola G7 Power, android 9. Memory is lots. I've got 2gb free out of 32gb on internal storage, 490+gb free on the SD card out of 512gb. RAM is 2.2gb out of 3gb used.

**Comment by ashutoshgngwr** [comment]
Greyed out is a feature because it made sense to disable controls if a sound wasn't playing,

**Comment by crogonint** [comment]
Well crap, I'll have to download the current version again. I'll do that later this this evening.

**Comment by crogonint** [comment]
Fixed in 3.4! 👯
