### ISSUE TITLE
Cricket Sound

### ISSUE THREAD

**Issue by crogonint** [ashutoshgngwr/noice#115]
Could we get the plain cricket noise back? I grew up being sung to sleep be crickets, and it was by far my favorite noise. The current one with the cicadas jars me awake every time the cicada chirps.. until I'm too tired to care.

In would suggest adding 'Crickets' to the list. I'm sure that there are plenty of people from the south who prefer the noise with the cicadas. ;)

**Comment by chagretes** [comment]
@crogonint something like this https://freesound.org/people/cs272/sounds/77034/?
Or maybe https://freesound.org/people/rucisko/sounds/250355/ ?

I don't know, it still looks a lot like the existing "night" sound.

**Comment by crogonint** [comment]
Beautiful! Well, the one is beautiful, the other has more white noise than
cricket. I would overlay these two:
Use 13 seconds of this (the end 13 seconds is more disjointed, will make it
seem more natural):
https://freesound.org/people/outdoor_recordings/sounds/362404/
with seven seconds of this:
https://freesound.org/people/cs272/sounds/77034/
..both repeating every time they end. Just make sure you don't cut a
cricket chirp in half and make it sound unnatural. That will make a
(relatively) clean sounding pair of crickets That will go on for perhaps
5-6 minutes before the same section of the 13 second clip match up with the
same timing of the 7 second clip. This should make the cricket noise sound
like it's not looping to the human ear.

Now, instead of looping two short clips, you COULD set them both to loop in
your audio app, then record the output for a minute or two, then simply
look for a clean cutoff point between both crickets chirping. However, the
human ear may detect that pattern repeating, and it needlessly uses up gobs
more storage. Also, in order to keep the human ear from detecting it as
easily, you'd have to record the full 5-6 minutes of disjointed pattern
until it starts repeating itself. Even more file space.

I did notice two puffs of white noise in one of the clips. I perfectionist
would pull those out as well, so the ear can't detect them repeating every
few seconds, forever.

For background noise, you might also add the BAREST layer of white noise to
one of the clips to emulate a light breeze waving grass (which is nearly
inaudible to even the best ears, anyway). You might even find a clip of a
breeze playing in the grass, then turn the level WAY down to where it's
barely audible. Then you could save that and layer it in to the cricket
noise and the cicada noise (if you want a separate cicada noise). ..or
perhaps even have it be a separate clip itself :)

A cicada makes an entirely different noise. Rarely in the deep south you'll
hear them singing (like a cricket) like this:
https://freesound.org/people/sinewave1kHz/sounds/207374/
That's rather pleasant, actually, but if you are going to put a cicada
noise in the app, it should be a separate selection from the cricket.
(preferably with a second cicada sound to mask the clip repeating itself).
Now then, the current 'night' sound, by contrast, has a long string of
cricket singing with a lone cicada chirping every 50 seconds or so (few
minutes? I don't recall). It's not horrible, but when I'm falling asleep,
that lone cicada noise jars me awake. It's almost as if he's yelling at the
crickets to shut up. ;)

FYI, I didn't forget about the project, I'm still working on getting all of
my resources together. I have like 25 external drives, and I haven't run
across my sound library yet. :/
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by chagretes** [comment]
Wow, you are really dedicated to the sound of crickets!

I can edit the sounds as directed. I'm just wondering if @ashutoshgngwr  will want two types of sounds so similar in the app.

If it is not his wish, I can generate an apk, changing the "night" to this new crickets sound and make it available to you ;)

_off topic: when I was a child I collected cicada shells (the exuviae). Their singing (at least the type here in my country) is very annoying_

**Comment by crogonint** [comment]
Oh, well, yes.. I grew up falling asleep to the sounds of crickets outside
my window. :)

Most of that was because we had previously discussed doing dual samples in
the app to make them not sound like a repeating loop. I'm actually not sure
if he's prepared to add that in to the app yet. ;)
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by ashutoshgngwr** [comment]
@crogonint @chagretes  I have already said it before. The idea mentioned in #62 is noble. I am willing to implement it but for audio editing for a inexperienced person is a tedious task. Dual samples made sense when you had earlier proposed them. If someone could go ahead and create dual samples for _looping_ sounds, we could try and experiment with it. If the results are satisfying, we can migrate all looping sounds in the library to use smaller (size-wise) dual samples. The other benefit I see is that with smaller samples, we could have more sounds in the library. Take a dedicated cricket sound for example.

My advice to anyone that want to do the sound editing bit.
1. Pick 2-3 looping samples from the sound library and download them from their original source.
2. Edit them as @crogonint has directed in this issue and #62 
3. Notify me so that I can make the code changes in the working branch. Or you could go ahead and do them yourself. Our goal here is to experiment with the results.

Most importantly, discuss the changes you are about to do beforehand so that your work doesn't go to waste.

**Comment by crogonint** [comment]
Yes, I just didn't know if Felipe was aware of the other conversation in
the other issue. ;)
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by chagretes** [comment]
I really wasn't aware of the other issue.
I believe I have time to do as @ashutoshgngwr  suggested. If I start working on it, I will communicate here before. That way we stay aligned

**Comment by ashutoshgngwr** [comment]
@crogonint https://www.youtube.com/audiolibrary_download?vid=c9c1711e0dfd1421 How about this sample for Crickets?

**Comment by crogonint** [comment]
Interesting.. Raw impression, it's very nice, two crickets, and appears to
have just a touch of background wind in it already. The audio isn't
particularly crisp, but you could enhance it and make it studio quality. I
don't care for the long intermission around 2/3 of the way through the clip
where the second cricket goes quiet for an extended period. That would very
hard to keep the human ear from picking up on if you made that part of the
loop. Still, the clip itself sounds perfectly natural. I would guess this
was recorded mid-spring, before the crickets start singing for hours and
hours without a pause, so they can attract the girl crickets. ;) Now, you
could add a third cricket in to help mask that long pause.. or just clip
the pause out entirely.

Something about the clip wasn't jumping out at me, so I put it in a
spectogram. There is indeed white noise on the low end. Either that is a
slow, steady wind, or somebody already added white noise to emulate it. You
MIGHT delete the white noise / wind and paste in something not QUITE so
steady over time to make it more interesting to the ear. Totally not
necessary though.

Look at the top end though. There is an intermittent pattern repeating
terribly quickly in the top end, around 8k. I'm not at all sure what that
is. Perhaps a street lamp or transformer, buzzing too high for the human
ear to detect it? Whatever it is, it ought to be cleaned out of the sample
before it is enhanced,

The sample appears to be a mono clip, converted to stereo. If you were
going to make your own clip, you might start our by putting 1 cricket(s)
2/3rds on the right channel, and 1/3rd on the left channel. Then do the
other cricket(s) 2/3rds on the left channel and 1/3 on the right channel,
to add some depth to the sound.

If you delete the wind and use your own more playful wind, you could
manually pan it back and forth from 2/3rds left to 2/3rds right to make it
feel like you're sitting right there in the field with the wind shifting
around. Then lower the level of the sample so that it's just louder than a
whisper.

That's about it. Really there's not much sense playing around with the
right and left channels though, since most android devices are basically
mono anyway.. unless you plug headphones in to it. You would get a lot more
bang for your buck just creating dual samples like I mentioned previously.
Ideally the sample lengths follow the golden ratio to last the longest
without repeating. 7 and 13 seconds gives you long enough samples to keep
them interesting with them being needlessly long. :)

I'll attach a screenshot of the spectogram below, but I'm writing this in
my email, I'm not at all sure if the picture will attack in the thread.
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.

**Comment by ashutoshgngwr** [comment]
Deferring all sound related changes to 0.9.x in favor of considering to work on #62 which would require rework on all sounds.
