### ISSUE TITLE
White font on white background when saving preset

### ISSUE THREAD

**Issue by pascalpa** [ashutoshgngwr/noice#126]
Hello,
When saving a preset with system default (light) theme, fonts appears white (or almost white) on a white background. Then, writing a description is very difficult.
 - Device: OnePlus 7t
 - Android Version: 10
Anyway, thank you for this app! It's GREAT!
Pascal, from Paris suburbs

**Comment by ashutoshgngwr** [comment]
Thank you for the feedback and report! I'll try to ensure that a fix is released with the next version.
