### ISSUE TITLE
Add sleep timer presets 

### ISSUE THREAD

**Issue by aproposnix** [ashutoshgngwr/noice#145]
### Add preset times
As a user, I would like to have some quick presets for the sleep timer as it currently takes too much effort to set the timer. For example, there could be buttons for:
* 1 hour 
* 2 Hours
* 4 Hours 
* 8 Hours

### Presets as the default - Time selector as advanced option
There should be a number of presets instead of the current radial dials (which can be confusing for tired people). Allow the user to select a specific time like it is now BUT present pre-sets before making the user have to hop through the loops of that radial dial. 

I guess the real point of this request is that the radial dial is not very nice. Image you are going to bed and don't have your glasses on... it's really hard to set that dial.

**Comment by ashutoshgngwr** [comment]
My nearsighted brain never thought of that. I'll see what I can do here.

**Comment by ashutoshgngwr** [comment]
@aproposnix New design in #148. There's also a screenshot. Let me know your thoughts.
