### ISSUE TITLE
What does timer slider do?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ashutoshgngwr/noice#172]
### Is your feature request related to a problem? Please describe.
I cant understand clearly what the small timer icon on some sound tracks EXACTLY does? (like sea belt beeps, distant thunder, or train horn.) I know that these tracks are non looping, and that the timer slider is maybe related to the gap between repetition, but i couldn't say exactly as i couldn't see the difference in the short trial.

### Describe the solution you'd like
Some about page here on gitlab, oops, github maybe.

Label can be ~support_question or smth like that.

**Comment by ashutoshgngwr** [comment]
I am sorry for the confusion. I've been thinking of adding descriptive text to the app to help users understand features better. The timer slider adjusts the upper bound in the delay between repetition of non-looping sounds. The minimum delay is fixed at about 30 seconds. At each repetition, a delay is randomly chosen.

**Comment by yashpalgoyal1304** [comment]
Awww, thats a nice implementation - random amount of delay, and ability to define the range. Thats why (randomness) I couldn't know it myself though.

As for the descriptive texts, i would say that maybe that will require many things which will maybe add clutter to UI. So, how about giving a link to a page here??

That way: 
- they will come to know the repository (idk if thats wanted though)
- the description can be updated fairly easily
- no effect (okay, no much effect) on the apps size and structure

**Comment by ashutoshgngwr** [comment]
Talk here: https://docs.google.com/document/d/1xxiAsCtqkf72oMN-ehWGWkmcB_2itz20b-Tx3apQTp4/edit?usp=sharing

**Comment by yashpalgoyal1304** [comment]
Thanks for the doc, but it was not much related to the issue. Just informing to not keep u waiting (:

**Comment by ashutoshgngwr** [comment]
Yeah sure man. I'll delete the doc in that case. About the concern regarding the clutter in the UI, I am open to implementing both ideas. A more in depth explanation can live on the web while short descriptive tips can popup in the app. I think the middle ground really does live up to the user experience. But that being said, I don't really have time to make detailed write up as of now and community around this project is still too small. I'll see what I can do but not promises.

**Comment by yashpalgoyal1304** [comment]
Just found out (and posting here for posterity's sake) that if a preset is playing, the parameters of its components can still be edited in library. (i dont know if they will be saved for next time though)

**Comment by ashutoshgngwr** [comment]
@yashpalgoyal1304 Yes. Editing is by design and no, they are not saved. You'll have to explicitly save the changes to a new preset. On a side note, I came across a bug about a few days ago where save preset button doesn't appear if you play a preset and then adjust a sound's volume or repetition time period.

**Comment by yashpalgoyal1304** [comment]
> Editing is by design

I guessed that, thanks for confirming and further info (:

The save button appears when u change sections. I was doing some further tests but couldnt replicate.
