### ISSUE TITLE
Sort in Library

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ashutoshgngwr/noice#173]
_(sort in title means for track order)_

### Is your feature request related to a problem? Please describe.
Similar tracks are not ordered/placed consecutively in Library.

### Describe the solution you'd like
_(idk how things work in backend, so if i say something, it means it seems like that to me - not that i know definitively)_
- Library is sorted alphabetically (implicit). So to follow that, the tracks name can be changed like `Moving train` --> `Train - moving` (i think it is called tree structure, idk)
    + `pro` minimum viable change (MVC) (even more minimal if
 sorting is automatic currently)
    + `con` naming can be criticised by some

- Alphabetic sorting can be replaced by Sorting by similarity
    + `pro` kinda nice middle ground (if current sorting is not automatic)
    + `con` mmm... some may say that the order seems kinda random

- There can be multiple options to sort
    + `pro` naming stays same
    + `con` not so minimal change in code, UX and UI

### Additional context

Brownian Noise
Pink Noise
White noise

Heavy rain
Light rain
Moderate rain

Distant thunder
Rolling thunder
Thunder crack

Moving train
Train horn

(Wind items can also be grouped, but i dont feel like they are similar enough)

**Comment by yashpalgoyal1304** [comment]
Somewhat related is the discussion at https://github.com/ashutoshgngwr/noice/issues/144#issuecomment-619366086

**Comment by ashutoshgngwr** [comment]
Sound groups will be needed if sound library grows. This feature was in the back of my head. I've been planning for implementation after #144 and hopefully #62. #62 gives Noice the edge of aggressively expanding its sound library.

For now, alphabetical sort is easier to work with, IMO.

**Comment by yashpalgoyal1304** [comment]
Is the sorting automatic as of now?

**Comment by ashutoshgngwr** [comment]
Not sure what you mean by automatic. Everything is sorted by hand here. Anything more than that seemed unnecessary at the time.

https://github.com/ashutoshgngwr/noice/blob/7b727d2cd698077a86d41685a50ebf2fddd83ad4/app/src/main/java/com/github/ashutoshgngwr/noice/sound/Sound.kt#L26-L54

**Comment by yashpalgoyal1304** [comment]
Glad u clarified. I was thinking that there were some collection of sounds. And library is just calling items from that collection and displaying it as a list. In that case the sorting would be automatic. I hope it makes some sense. I dont know how that is implemented though.

**Comment by ashutoshgngwr** [comment]
@yashpalgoyal1304 We'll come to it when we come to it.

**Comment by ashutoshgngwr** [comment]
@yashpalgoyal1304 My last remark was in the spirits that currently we don't have this in planned sight so we come it when we come to it. Worrying about its implementation details will only take focus off of things that are currently planned.
