### ISSUE TITLE
Add AMOLED theme

### ISSUE THREAD

**Issue by julianrrr** [ashutoshgngwr/noice#180]
### Describe the solution you'd like
Add new theme to Amoled display's. Something similar to attached screenshot.

### Additional context
![AMOLED theme](https://cdn.neow.in/news/images/uploaded/2019/11/1573495267_discord-amoled-dark-theme-1.jpg)

**Comment by ashutoshgngwr** [comment]
> The non-black (or non-amoled) theme is a conscious choice all the while keeping the OLED and AMOLED displays in consideration. The rationale behind the decision was that the power consumption difference between full black and dark theme isn't very significant. Even Google won't use full black themes in their apps. In addition to this, my assumption is that an average user won't need to spend much time actually "seeing" the app.

This was my response to a discussion via email at earlier time. I still stand by it. I don't really understand the hype around all black themes? Is there something else that I might be missing? :curious:

**Comment by julianrrr** [comment]
Yes, I know it. But I like to have all applications with similar themes if is possible. I could also try to add the them, I don't know if it involves too many changes

**Comment by ashutoshgngwr** [comment]
@julianrrr Will give it a thought. Right now, the focus is on planned features and issues.
