### ISSUE TITLE
(BUG) (noice Current Version 0.2.5) App failed to open

### ISSUE THREAD

**Issue by friendsmobile** [ashutoshgngwr/noice#20]
# Project Information

* Repository: https://github.com/ashutoshgngwr/noice
* Project Name:  noice
* My Github Account: https://github.com/friendsmobile
* Download the application:  https://play.google.com/store/apps/details?id=com.github.ashutoshgngwr.noice

# Expected behavior

When I open the application, all feature should appear and the application should not be crashed.

# Actual behavior

The application crashes when I open the application

#### How to reproduce

* [Download ](https://play.google.com/store/apps/details?id=com.github.ashutoshgngwr.noice)the application
*  open the application 
* Note the Error

* Browser/App version:   Current Version 0.2.5
* Operating system: 6.0

#### Recording Of The Bug

![20190711_151904](https://user-images.githubusercontent.com/51118734/61043826-15eb4580-a38c-11e9-8b7e-32730e0c467a.gif)

#### Logcat

<pre><code>D/AndroidRuntime(17855): Shutting down VM

E/AndroidRuntime(17855): FATAL EXCEPTION: main

E/AndroidRuntime(17855): Process: com.github.ashutoshgngwr.noice, PID: 17855

E/AndroidRuntime(17855): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.github.ashutoshgngwr.noice/com.github.ashutoshgngwr.noice.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class com.google.android.material.navigation.NavigationView

E/AndroidRuntime(17855): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)

E/AndroidRuntime(17855): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2769)

E/AndroidRuntime(17855): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)

E/AndroidRuntime(17855): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)

E/AndroidRuntime(17855): 	at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(17855): 	at android.os.Looper.loop(Looper.java:135)

E/AndroidRuntime(17855): 	at android.app.ActivityThread.main(ActivityThread.java:5910)

E/AndroidRuntime(17855): 	at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(17855): 	at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(17855): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)

E/AndroidRuntime(17855): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

E/AndroidRuntime(17855): Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.google.android.material.navigation.NavigationView

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)

E/AndroidRuntime(17855): 	at b.b.a.x.b()

E/AndroidRuntime(17855): 	at b.b.a.m.setContentView()

E/AndroidRuntime(17855): 	at com.github.ashutoshgngwr.noice.MainActivity.onCreate()

E/AndroidRuntime(17855): 	at android.app.Activity.performCreate(Activity.java:6178)

E/AndroidRuntime(17855): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)

E/AndroidRuntime(17855): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2648)

E/AndroidRuntime(17855): 	... 10 more

E/AndroidRuntime(17855): Caused by: java.lang.reflect.InvocationTargetException

E/AndroidRuntime(17855): 	at java.lang.reflect.Constructor.newInstance(Native Method)

E/AndroidRuntime(17855): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)

E/AndroidRuntime(17855): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)

E/AndroidRuntime(17855): 	... 21 more

E/AndroidRuntime(17855): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070077

E/AndroidRuntime(17855): 	at android.content.res.Resources.getValue(Resources.java:1542)

E/AndroidRuntime(17855): 	at b.b.f.ca.d(:4)

E/AndroidRuntime(17855): 	at b.b.f.ca.a(:11)

E/AndroidRuntime(17855): 	at b.b.f.ca.b()

E/AndroidRuntime(17855): 	at b.b.b.a.a.c()

E/AndroidRuntime(17855): 	at b.b.e.a.o.getIcon(:2)

E/AndroidRuntime(17855): 	at c.c.a.a.n.j$b.c(:5)

E/AndroidRuntime(17855): 	at c.c.a.a.n.j.a(:1)

E/AndroidRuntime(17855): 	at com.google.android.material.navigation.NavigationView.c()

E/AndroidRuntime(17855): 	at com.google.android.material.navigation.NavigationView.<init>(:24)

E/AndroidRuntime(17855): 	at com.google.android.material.navigation.NavigationView.<init>()

E/AndroidRuntime(17855): 	... 24 more
</code></pre>

**Comment by ashutoshgngwr** [comment]
@friendsmobile Thanks for the report. I'll look into it! :+1:

**Comment by ashutoshgngwr** [comment]
@friendsmobile Neither can I reproduce this, nor do I have any logs available for such crash in Google Play Console.
