### ISSUE TITLE
Time duration between various sounds

### ISSUE THREAD

**Issue by devansh00712131** [ashutoshgngwr/noice#202]
It will be very nice addition to the app and will make it stand different for every other app if the time between the sound, for example thunders or rain drops or village sound were randomised

**Comment by ashutoshgngwr** [comment]
Did you mean #144?

**Comment by devansh00712131** [comment]
Similar to that but much simpler, just add a random number generator
(between 40 to 60 seconds) and let the sound come at that second interval.
I noticed that the distant thunder was repeating every 47 second

**Comment by ashutoshgngwr** [comment]
> I noticed that the distant thunder was repeating every 47 second

Weird. This shouldn't happen because interval is chosen at random for each iteration. So It shouldn't be fixed.

Besides that, 144 is planned and will be implemented.

**Comment by ashutoshgngwr** [comment]
Closing this in favour of #144. Also, I investigated for time intervals for each repetition, the random interval selection logic works fine. I am not sure how you reached the conclusion that distant thunder was repeating every 47 seconds.
