### ISSUE TITLE
FDroid link to changelog.md

### ISSUE THREAD

**Issue by sudomain** [ashutoshgngwr/noice#213]
### Is your feature request related to a problem? Please describe.
Thank you for the great app. I'm not sure what this entails or if a change is even needed on this side of things. The FDroid page appropriately links to the source code, website, issues, and other related pages for this project, but it is missing a link to your changelog.md.
### Describe the solution you'd like
A link to the changelog within the FDroid app, like other FDroid apps have.

**Comment by ashutoshgngwr** [comment]
@sudomain I didn't think that was necessary since change log for latest version is displayed from `fastlane/metadata/android/en-US/changelogs`. But I'll add it there, just in case.

**Comment by ashutoshgngwr** [comment]
Resolved by [this merge request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7097) in F-Droid Data Repository.
