### ISSUE TITLE
Suggestion for new sound

### ISSUE THREAD

**Issue by shom13** [ashutoshgngwr/noice#215]
Hello, firstly lovely app. Would love it even more if you could add a few more sound options like

- Soft Piano sound(many the merrier)
- The current windchime sound is good, but not as peaceful
- Bells and other sound for meditation
- Binural beats

I hope you could add these to the already awesome collection of sounds in your app. 

Thank you

**Comment by shom13** [comment]
Soft peacuful Piano sound along with rain is a potent mix for instant inner peace. I understand finding royalty free music is difficult. Hence here is a link to royalty free peaceful piano tunes. 

https://www.fesliyanstudios.com/royalty-free-music/downloads-c/peaceful-and-relaxing-music/22

Plenyy of peaceful tunes there.Hope you could add them if its not much of a hastle.

**Comment by eanema** [comment]
I'm not sure if it would be preferred to start a new issue, but I figured it's close enough to this issue to piggyback. I would like to make another suggestion for a new sound. I have a newborn baby at home and we have been using this app as a noise generator for her. It is wonderful, exactly what I wanted, simple, NOT just an mp3 player, and loops indefinitely. Thanks for this. 

Now the new sound suggestion is for a heart beat sound effect, like a baby would hear in the womb. The first Google hit is basically what I'm talking about:
https://youtu.be/J7nyM0F_2C4

Thanks for the great work!

**Comment by ashutoshgngwr** [comment]
Hi @eanema,

The work has been slow lately. Will definitely try to add this. Meanwhile, you can play Noice alongside YouTube using the following steps
1. Play desired sounds in Noice
2. Play whatever you want on YouTube (This will cause Noice to pause)
3. Resume Noice from its Notification (This will not stop YouTube and both apps can play simultaneously)

**Comment by samuzamu** [comment]
Hi!
Found this app recently. It's excellently made. I love it. I do have a sound suggestion though.
I want this sound of a distant murmur, like the sound of a small group having a quiet conversation in another room.
Would love if you'd consider it :)
I have a few examples in the general tone I'm thinkig of:
https://freesound.org/people/tfsound/sounds/82171/
https://freesound.org/people/SpliceSound/sounds/260121/

**Comment by ashutoshgngwr** [comment]
@shom13 It doesn't make sense to mix musical instruments with ambient sounds in the app. This is exactly the reason why I designed Noice with such that it can play alongside other music players. I myself tune in Piano with a little ambience to achieve Nirvana. :)

**Comment by ashutoshgngwr** [comment]
@samuzamu added to in my todo-list. Working on the next update. Should be out in about a week.

**Comment by ashutoshgngwr** [comment]
I have added whatever suggestions made sense to me. If you still think that I've missed something or have more suggestions, feel free to open up a new issue. Please do not add suggestions to existing issues. It makes it really hard to track.
