### ISSUE TITLE
Autoplay continue after interruption

### ISSUE THREAD

**Issue by asuh** [ashutoshgngwr/noice#219]
Love this app and it's potential! Already deleted another that does similar :)

Maybe this is isolated to my Samsung Galaxy S7, but I noticed that after an alarm turned on (set in the Clock app), I dismiss the alarm to turn it off but Noice didn't immediately play again, or restart the sound, as I expected? It'd be great for this feature to be updated to continue after the interruption is dismissed.

**Comment by ashutoshgngwr** [comment]
Hi @asuh!

Thanks for the report. No, the behaviour you're describing is unexpected. Recently Noice had gone through major code changes and it's likely that this bug got introduced in these changes. I'll investigate the issue further and fix this as soon as possible.
