### ISSUE TITLE
Playback time limit?

### ISSUE THREAD

**Issue by asuh** [ashutoshgngwr/noice#220]
Using this on my Galaxy S7, I've let this play through the night since I installed it. I've noticed that it appears to stop on its own after about 7 hours of continuous playback. Is there a time limit to the playback that cuts it off after a certain period of time? I don't set a timer, just opened the app and started the sound I wanted.

**Comment by ashutoshgngwr** [comment]
@asuh We impose a timeout of 1 day on wake locks. This means that playback, in theory, should continue to play unless wake locks are released. We don't impose any other limits on playback. We've had another report of a similar issue in the past but it is hard to reproduce this and capture logs of the failure.

PS, if you encounter this again, can you take a note of app's memory usage for the last session. It can be generally found in **Settings > System > Developer Options > Memory**.

It might also be worthwhile to try turning off battery optimisations for Noice. It is generally available in **Settings > Apps > Noice > Battery**.

From my end, I had been able to reproduce this once with an older version of Noice. But, I was unable to capture any logs or perform a detailed analysis. I'll try to reproduce this again and see if I get lucky this time.

**Comment by asuh** [comment]
I turned battery optimization off for Noice and the result was good, it kept going. I will keep monitoring this but I think this might be a fix.

**Comment by ashutoshgngwr** [comment]
@asuh If that turns out to be the case, then there's nothing we can do about it in the app except putting up a message that tells users to turn off battery optimizations. At any rate, please keep me updated.

**Comment by asuh** [comment]
Thanks for the reminder stalebot. I think your suggestion to turn off battery optimization for Noice was the permanent fix so we're good here!
