### ISSUE TITLE
Loudness Equalization

### ISSUE THREAD

**Issue by GittyBruce** [ashutoshgngwr/noice#227]
I love the app, but I find that sudden loud peaks in the audio are disruptive and distracting and undermine the whole relaxation aspect of using the app.

It would be great to get an option to enforce loudness equalization i.e. decreasing the volume difference between the highest and lowest volume parts of a track.

**Comment by GittyBruce** [comment]
I just went ahead and equalized the sound files manually in the apk. Would still be nice to have loudness equalization, but the app is now usable for me without it so I'm closing this issue.

**Comment by ashutoshgngwr** [comment]
Hey @GittyBruce 

I tried to apply loudness normalization effect in Audacity on sounds and it didn't really work as I expected. Most sounds were getting amplified as far as I remember. I don't have much expertise with audio editing. More tips might be useful here.

**Comment by GittyBruce** [comment]
hey @ashutoshgngwr 

in audacity, the loudness normalization effect is intended to equalize the loudness across multiple tracks. It sets the loudness of a track to a certain level. Applied to multiple tracks, it sets them all to the same level of loudness.

The loudness equalization I was looking for is best done with the compressor effect (my settings in pic attached). This will compress volumes above a loudness threshold.

More info here: https://en.wikipedia.org/wiki/Dynamic_range_compression#Controls_and_features

![image](https://user-images.githubusercontent.com/68361737/91911747-96db5f80-ec66-11ea-9ec0-3a5eb0deaa5d.png)

**Comment by ashutoshgngwr** [comment]
So I applied an Audacity macro to batch process the effect. I was able to get workable output for 21/35 sounds. The rest of the samples didn't produce a workable result and I am omitting them for now.
