### ISSUE TITLE
Market icon has no background and looks bad in the dark mode

### ISSUE THREAD

**Issue by 532910** [ashutoshgngwr/noice#250]
While in launcher the icon looks nice:
![image](https://user-images.githubusercontent.com/14617699/88481981-31a99580-cf67-11ea-9b90-147cb573490b.png)

In F-Droid:
![image](https://user-images.githubusercontent.com/14617699/88481926-e42d2880-cf66-11ea-9001-9a6071542b10.png)
![image](https://user-images.githubusercontent.com/14617699/88481976-26566a00-cf67-11ea-84a6-43067305e350.png)

and GPlay:
![image](https://user-images.githubusercontent.com/14617699/88482339-47b85580-cf69-11ea-8c38-bd337514a63d.png)
![image](https://user-images.githubusercontent.com/14617699/88482285-f9a35200-cf68-11ea-9b51-d09ec50fcfba.png)

it has no background and is invisible.

**Comment by ashutoshgngwr** [comment]
Thanks for the report. You can expect this to be fixed in the next release.
