### ISSUE TITLE
Saved sound combination duplicated after sleep timer screen or wake up timer screen is opened 

### ISSUE THREAD

**Issue by samuzamu** [ashutoshgngwr/noice#252]
### Describe the bug
My list of custom saved sound combinations is duplicated twice, after I've opened either of the timer screens and then go back to the sound combinations screen. If I click on one of the duplicated listings, multiples of the same combinations begin playing. If I then click to stop one of the ones playing, the remaining ones keep playing.

### To Reproduce
1. Go to 'sleep timer or wake up timer'
2. Go to 'saved combinations'
3. Scroll down the list
4. See that all the entries are duplicated

### Expected behavior
I expect the list of saved sound combinations to remain the same, wether I have opened either of the timer windows or not.

### Screenshots
![Screenshot_20200729-194008](https://user-images.githubusercontent.com/68883568/88833946-628e0280-d1d3-11ea-86f9-8e55eba0ff81.png)
![Screenshot_20200729-194028](https://user-images.githubusercontent.com/68883568/88833952-66218980-d1d3-11ea-8e03-bd461e8b8920.png)

### Others
 - Device: Motorola Moto G6
 - Android Version: Pie 9.0

**Comment by ashutoshgngwr** [comment]
Thanks for the report @samuzamu. I am able to reproduce this and will fix it ASAP.
