### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [ashutoshgngwr/noice#26]
### Is your feature request related to a problem? Please describe.
I'm always frustrated when [...] I can find an app only on Play Store, with no privacy-friendly alternative. I don't use Play Store at all; all my devices run LineageOS without GApps, and have F-Droid instead.

### Describe the solution you'd like
I'd like to see the app available in an alternative place – like, at F-Droid, or at least the APK here at Github (ideally attached to its corresponding `releases/`).

### Additional context
Uhm, if you ask so directly: With the APK available here, I could immediately pick it and add it to [my repo](https://apt.izzysoft.de/fdroid), which can be used with the F-Droid client. I also gladly assist in bringing your app to the official repo, if you wish so.

**Comment by ashutoshgngwr** [comment]
As much as I'd like to do that, I had configured Noice's APKs to be signed by Google Play. To avoid any install conflicts for majority users (which I think comes from Google Play), I have religiously avoided uploading binaries signed with my certificate to any other source, although I am starting to regret that decision now.

Anyways, I've created an [RFP](https://gitlab.com/fdroid/rfp/issues/1045)! I hope its adequate.

**Comment by ashutoshgngwr** [comment]
@IzzySoft Let me know if there's anything else I need to do in order to complete the process!

**Comment by IzzySoft** [comment]
Hey cool, that's the better solution anyway, thanks! I'll wait overnight until the bot has checked, and then prepare it for the next step, which is packaging (disclosure: I'm one of the F-Droid maintainers). Thanks a lot!

(PS: just as a note, not critićising: handing your private key to a third party is something you should avoid for security reasons. That third party now can manipulate your packages to its liking – e.g. add trackers, ads or other sneaky things – regardless how they sell "the service" to you)

**Comment by rancidfrog** [comment]
Having apk|APKs in releases is useful, even when signed by 3rd-party(unfortunately)
I.E.
https://github.com/TwidereProject/Twidere-Android/releases
![](https://i.imgur.com/uPUJzG9.png)

**Comment by IzzySoft** [comment]
@rancidfrog just note that the names of those APKs rather reflect the flavor they were build from than the signing party. Usually, such attached APKs are signed by the developers themselves. I never encountered an exception to that yet (though admittedly I didn't "keep watch").
