### ISSUE TITLE
Can I import local audio?

### ISSUE THREAD

**Issue by dyxang** [ashutoshgngwr/noice#270]
There is a little bit less audio in the library, I think I can customize Then import the white noise audio file from the phone
Will there be such a function in the future? ：）

**Comment by ashutoshgngwr** [comment]
This was discussed in #142. No, we don't have any plans to support custom sounds. You can refer to the original issue for further clarification. If you want to play your own sounds however, you can play them using any other audio player and play Noice alongside it.

**Comment by ashutoshgngwr** [comment]
I am marking this as closed. If you have any questions, feel free to continue the conversation. :)
