### ISSUE TITLE
Chromecast Speaker Groups

### ISSUE THREAD

**Issue by amck1nnon** [ashutoshgngwr/noice#283]
Hi there,

There appears to be an issue playing to Chromecast speaker groups

In my own testing, audio seems to only be sent to one of the speakers in the group

In my case, I am attempting to play to two speakers, one a JBL Link 10 and the other a Sony LF-S50G.

This is a pretty highly desirable feature for me, because it helps enormously with the believability of the generated sound.

Thanks (:

**Comment by ashutoshgngwr** [comment]
@amck1nnon Hi!

This was my first attempt at a Chromecast app. Although I don't have multiple devices to test this, I'll see if there's anything obvious that I might have missed.

**Comment by amck1nnon** [comment]
I appreciate the work and I've popped a donation in through the app. For anyone wondering: I found a workaround (at least in my case) thanks to my phone letting me output the phone's audio to Chromecast rather than needing to go through an app at all. 

Thanks (:

**Comment by ashutoshgngwr** [comment]
@amck1nnon That's good to know. Thank you for your support.

PS I was wondering when you used the Noice to cast audio, was it always the same speaker at fault or one of them would play randomly? I think it should be an out of memory thing if it was the same speaker that was at fault every time you were trying to cast. If that's not the case, then this a definitely a bug.
