### ISSUE TITLE
BBC Sound Effects as possible audio source

### ISSUE THREAD

**Issue by patzi** [ashutoshgngwr/noice#361]
The BBC has released 16000 sound files see http://bbcsfx.acropolis.org.uk/
I couldn't find the conditions under what kind of licence a file could be added to noice. So maybe the licence of the files does not fit to noice.

> These 16,000 BBC Sound Effects are made available by the BBC in WAV format to download for use under the terms of the [RemArc Licence](https://github.com/bbcarchdev/Remarc/blob/master/doc/2016.09.27_RemArc_Content%20licence_Terms%20of%20Use_final.pdf). The Sound Effects are BBC copyright, but they may be used for personal, educational or research purposes, as detailed in the license.

**Comment by ashutoshgngwr** [comment]
I don't think the license permits redistribution of sounds. Their homepage has the following link

> For commercial use, you can [license sound effects.](https://blog.prosoundeffects.com/how-to-license-bbc-sound-effects-to-use-in-your-commercial-productions)

That page mentions the following

> Our default license includes:
> - 100% Royalty-Free
> - Commercial Synchronization
> - All Media
> - Worldwide
> - Unlimited Usage by 1-User

I think _Unlimited usage by 1-user_ implies no redistribution.

PS, it's a good source to use in future sound suggestions. I'll try to contact them via email and ask for clarification.

**Comment by JekRock** [comment]
Here is what the license states:
> - For non-commercial, personal or research purposes(for example, including the content on a non-commercial, advertisement-free reminiscence website aimed at helping trigger memories in people with dementia)
> - For formal education purposes while you are a student or a member of staff of a school, college or university(for example, if you are enrolled on a university or college course, or if you are a school pupil, or you are a teacher and you wish to display the content on an electronic whiteboard, including images in a printed classwork sheet)
> 8.Using BBC content forbusiness
> a)When you need permission
> If you’re intending to use it for any other purpose, for example....
> - substantially to do your job–as an employee, contractor or consultant
> - for commercial purposes – to make a profit
> - for non-profit and government organisations
> ...you’ll need to get our permission first, and you might have to pay a fee. Find out more about getting permission to use BBC content at http://www.bbc.co.uk/helpandfeedback/use-material

So, it's definitely better to ask the permission first

**Comment by ashutoshgngwr** [comment]
I am closing and pinning this issue since it's not really an issue and more of an additional resource for future contributions/contributors.
