### ISSUE TITLE
Noice is great app, Please port to OSX and FreeBSD

### ISSUE THREAD

**Issue by akissz** [ashutoshgngwr/noice#399]
The noise app is great and good for people with disabilities. Please can someone start to port this app to computer operating systems, for example I would like both OSX and FreeBSD. I can see myself using the app at night. But I do not personally use a phone at night. But I use a computer. So having the computer option would be very good.

**Comment by ashutoshgngwr** [comment]
I am closing this for now since it is way out of scope for this repository. If someone wants, they can port it to macOS and other platforms as Noice is covered by the MIT license which gives them every right to do so.

**Comment by ashutoshgngwr** [comment]
Track further progress in https://github.com/ashutoshgngwr/noice/discussions/488!
