### ISSUE TITLE
Allow user-supplied audio samples

### ISSUE THREAD

**Issue by JonTabor** [ashutoshgngwr/noice#40]
Some of the samples are small enough to have a noticeable pattern when repeating, which can be distracting.  While pondering possible solutions, I thought it would be a great feature (and solve the issue) if users were allowed to supply their own samples.

**Comment by ashutoshgngwr** [comment]
The problem with short sound loops is inherent from the Android's SoundPool framework which has very strict memory limitations. To solve it, one would need to rewrite Noice's SoundManager with MediaPlayer or other relevant framework.

Giving user's ability to import their own sounds will also be bound by SoundPool's limitation and isn't a good idea given Noice's current state. I'll keep this open just in case if I or someone else decides to rewrite Noice's SoundManager.

**Comment by ashutoshgngwr** [comment]
I am still skeptical about having user-supplied samples, but nonetheless, I have started working on a new version of SoundManager which will allow for better quality with longer sound loops.
