### ISSUE TITLE
The Noice notification Player drains the battery

### ISSUE THREAD

**Issue by franciscot** [ashutoshgngwr/noice#426]
### Describe the bug
Sometimes Noice drains my battery. I can see that Noice's player appears in the notification when I turn on or off a headset. Even if Noice is not being used or is closed.

### To Reproduce
1. Noice is "closed" or not using
2. Plug or unplug headset.
3. Noice opens notification player.
4. Turn off my tablet. (sleep mode)
5. Noice drains my battery while my tablet is on sleep mode.

### Expected behavior
Noice doesn't run when you plug or unplug a headset.

### Others
 - Device:  Nexus 7 2013 wifi (flo)
 - Android Version: Lineage os 14.1 (Android version 7.1.2)

Example, Noice drained 30% of the battery in one night:
![nexus 7 ](https://user-images.githubusercontent.com/5504418/101164623-98d20780-3635-11eb-8f8e-c80ace51c9c1.jpg)

**Comment by ashutoshgngwr** [comment]
Hi @franciscot!

This is (was) the intended behavior. Noice expects an user to manually _stop_ the player from the notification. Hence, the current behavior will pause the playback when you unplug the headset, but Noice won't release its resources unless you click the _stop_ button from the notification. I can see why this should not be the intended behavior.

PS, in some other cases, e.g. when you start another media player, Noice is set to pause the playback. If user doesn't resume the playback within 1 minute (now I am setting it to 5 minutes), Noice completely shuts down releasing all its resources. I am extending the same behavior to this case.

**Comment by ashutoshgngwr** [comment]
I have fixed this, but you'll have to wait for the next release. Until then, consider manually stopping Noice from the notification after unplugging headphones.

**Comment by franciscot** [comment]
Thank you very much @ashutoshgngwr 
Great Job!
