### ISSUE TITLE
Translation help for strings.xml

### ISSUE THREAD

**Issue by berkaygunduzz** [ashutoshgngwr/noice#427]
I can't find these strings in app and their translations depends on usage, what they are represent or how can i find them in app?
- repeat_time_period
- later
- never
- mood
- any
- focus
- relax
- intensity
- intensity_description
- dense
- light

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz 

- repeast_time_period &mdash; content description for accessibility tools https://github.com/ashutoshgngwr/noice/blob/15acf89b7cdb3c0b53c9bbc56f9baa8fdada2f50/app/src/main/res/layout/sound_list_item.xml#L75
- later, never &mdash; In in-app review modal that is shown randomly in F-Droid app variant https://github.com/ashutoshgngwr/noice/blob/15acf89b7cdb3c0b53c9bbc56f9baa8fdada2f50/app/src/fdroid/java/com/github/ashutoshgngwr/noice/InAppReviewFlowManager.kt#L55-L56
- all others &mdash; on clicking the shuffle button from starting screen &mdash; https://github.com/ashutoshgngwr/noice/blob/master/app/src/main/res/layout/dialog_fragment__random_preset.xml

**Comment by berkaygunduzz** [comment]
Thanks, and also, for about fragment, is it must to add region? my translation is only tr, should i convert it to tr-TR?

**Comment by ashutoshgngwr** [comment]
I am not sure if I am the best person to answer that. If your translations are applicable to a specific region, I'd suggest you use the regional qualifiers everywhere. If you're providing generic translations that applies to all the regions, you can leave out the regional qualifier.

**Comment by berkaygunduzz** [comment]
Ok, i think i will leave region. Thanks again for your help.
