### ISSUE TITLE
Tidying up the 'strings.xml' files

### ISSUE THREAD

**Issue by berkaygunduzz** [ashutoshgngwr/noice#442]
### Is your feature request related to a problem? Please describe.
When i translate, it was hard to find out where am i and where is the string that i will control.

### Describe the solution you'd like
I want to group strings and make topic comments to their head for all string.xml files.
Group names that i suggest:
- Navigation Drawer
- Library
- Saved Presets
- Sleep Timer
- Wake-up Timer
- Theme
- About
- Help
- Support Development
- Buttons
- Others

An example:
```xml
  ...
  <!-- Navigation Drawer -->
  <string name="library"></string>
  <string name="about"></string>
  <string name="report_issue"></string>
  ...

  <!-- Library -->
  <string name="airplane_inflight"></string>
  <string name="airplane_seatbelt_beeps"></string>
  <string name="birds"></string>
  ...
```

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz While this sounds awesome, you'll have to do it for all the locales to keep things consistent. I'm open to accepting these changes if you're upto it.

**Comment by berkaygunduzz** [comment]
Great, i will start it as soon as possible.

**Comment by berkaygunduzz** [comment]
@ashutoshgngwr How it looks like? This is a draft and it will be alphabetical. If you have suggestions i'm open to them.
[strings.xml](https://github.com/ashutoshgngwr/noice/files/5661428/strings.xml.txt)

Btw, i won't make it hand by hand, i will make a Python script that will do it. Also i will share it when finished.

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz  Yeah, this works! Much better than the what we have now.

**Comment by berkaygunduzz** [comment]
I don't have a full perfection on app so when you have time, can you control that all strings are in correct topic?

**Comment by ashutoshgngwr** [comment]
I made a few changes and added more granular sections. I accidentally replaced 3-blank lines by 2-blank lines. You can keep whichever you prefer.

[strings.xml.txt](https://github.com/ashutoshgngwr/noice/files/5661560/strings.xml.txt)

**Comment by berkaygunduzz** [comment]
Looks great, thanks.

**Comment by berkaygunduzz** [comment]
@ashutoshgngwr Because of my text editor (gedit) , it converted special chars to codes. Is it problem? How can i fix it? Here is [commit](https://github.com/berkaygunduzz/noice/commit/86add4ce01f86d358b5aff372e4ee8c8f6d9d10b)

**Comment by ashutoshgngwr** [comment]
Yeah, I don't think it will render correctly. PS, you can try another code editor like [VSCode[(https://code.visualstudio.com/download).

**Comment by berkaygunduzz** [comment]
Ok, i will try to fix it.

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz Ignore that comment. As you said, it was the script that did this. Let me see if I can find a fix.

**Comment by ashutoshgngwr** [comment]
Could you please share your script so that I know what I am dealing with?

**Comment by berkaygunduzz** [comment]
It's a bit messy. Tested and worked with Python 3.8.6
[tidy.zip](https://github.com/ashutoshgngwr/noice/files/5665890/tidy.zip)

**Comment by berkaygunduzz** [comment]
Script doesn't makes sense with tabs, i made them manually.
Btw, I can fix it with [this](https://www.branah.com/unicode-converter)

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz On line 38, if you pass another parameter `encoding="UTF-8"`, it will write strings as UTF-8 byte sequence. I tested it, it fixes the issue.

Ref: https://stackoverflow.com/questions/10046755/write-xml-utf-8-file-with-utf-8-data-with-elementtree

**Comment by berkaygunduzz** [comment]
Well, that's great. Thanks

**Comment by berkaygunduzz** [comment]
Do you want me to delete topic comments if it has no strings?

**Comment by ashutoshgngwr** [comment]
Yeah, you can delete the empty ones.
