### ISSUE TITLE
Community maintained presets

### ISSUE THREAD

**Issue by ashutoshgngwr** [ashutoshgngwr/noice#447]
A few presets (about 5?) hand-picked by the community that will be shipped with Noice.

Pending discussion! Feel free to leave your thoughts.

**Comment by berkaygunduzz** [comment]
What about environmental presets?
For example a seaside camp:
Birds %5
Seagulls %15 2m
Bonfire %50
Seaside %30
Soft Wind %20
That's just a draft but what about that idea?

**Comment by ashutoshgngwr** [comment]
@berkaygunduzz That's a great example, but I think we should normalize volumes to the maximum. What I mean is that we can set Bonfire to 100% in your example and adjust all others in proportion.

I was also thinking that we can keep this issue open so that more people can pitch their presets and vote on them using reactions. After we have enough data, we can pick the top 5 presets and take it from there.
