### ISSUE TITLE
Text overflow with large font-size in App Intro slides

### ISSUE THREAD

**Issue by franklinbill** [ashutoshgngwr/noice#458]
### Describe the bug
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 0.14.0, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="467" alt="bug-noice_36-2" src="https://user-images.githubusercontent.com/18572115/103166670-6ba4fd80-485f-11eb-830b-2318f228544b.png">

### To Reproduce
1. Go to first page
2. See error

### Expected behavior
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

### Screenshots
<img width="467" alt="bug-noice_36-2" src="https://user-images.githubusercontent.com/18572115/103166685-8a0af900-485f-11eb-8365-ec5f1da35f7d.png">

### Others
 - Device: [e.g. Xiaomi Redmi 3 Prime] Google nexus 6
 - Android Version: [e.g. Oreo, 8.1] Android 8.0

**Comment by ashutoshgngwr** [comment]
@franklinbill Thanks for reporting the issue. Please consider the following

1. We use [AppIntro](https://github.com/AppIntro/AppIntro) component to display these slides.
2. This portion of the app is not critical. It doesn't add any functionality besides explaining what the app does.

I see you've already opened an issue at https://github.com/AppIntro/AppIntro/issues/915. I'll try to find time to work on the original upstream issue, but it is unlikely to get fixed from our end.

If you notice any other font-size related problems in the rest of the app, please let us know.
