### ISSUE TITLE
Add shortcut to set "Saved Presets" as app's starting screen

### ISSUE THREAD

**Issue by ashutoshgngwr** [ashutoshgngwr/noice#469]
### Is your feature request related to a problem? Please describe.

From https://news.ycombinator.com/item?id=25682114

> the only issue I had was (relatively minor) UI difficulty - there was no way to set 'saved presets' as the home screen of the app. So every time, I had to open the app, open the side bar, click on Saved Presets (which was pretty much the only things I wanted to play), then click on the preset title. Making this easier might be nice for other users who might have the same issue. Relatedly, widgets would be nice to have - just a simple 1x1 Play button, that when clicked starts playing a particular Saved Preset chosen when creating the widget. 

### Describe the solution you'd like

I have three potential solutions in mind.

1. Add a setting to make "saved presets" initial screen on opening the app.
2. Make both "library" and "saved presets" tabs on the initial screen.
3. Allow users to add a launcher shortcut for opening "saved presets" directly.

**Comment by szmt** [comment]
I vote for solution 1.
