### ISSUE TITLE
Add your own sound feature

### ISSUE THREAD

**Issue by FedericoConcas** [ashutoshgngwr/noice#479]
### Is your feature request related to a problem? Please describe.
Instead of creating an endless list of sounds based on user requests, you could just keep the curated list as it is and allow users to import and play their own sounds.

### Describe the solution you'd like
An import button allows you to load a sound and name it.
With reference to the BBC sounds and licences, the BBC licence mentions personal use so this could be an ideal solution.

**Comment by ashutoshgngwr** [comment]
Closing in favor of https://github.com/ashutoshgngwr/noice/discussions/452.
