### ISSUE TITLE
Elements are missing in the menu on tablets

### ISSUE THREAD

**Issue by MakiWolf** [ashutoshgngwr/noice#484]
### Describe the bug
"Library" and "Saved Presets" are missing in the menu on tablets

### To Reproduce
1. Open the app
2. Open Menu

### Screenshots
![issue](https://user-images.githubusercontent.com/73300633/106064537-550df280-60fa-11eb-9c84-147ce52d5c8f.gif)

![grafik](https://user-images.githubusercontent.com/73300633/106064561-5ccd9700-60fa-11eb-8c14-e5e76b6cf5eb.png)

### Others
 - Device: Tablet 13.5" Freeform from Android Studio Emulator
 - Android Version: 11

**Comment by ashutoshgngwr** [comment]
Wierd. Will check it out. Thanks for the report!
