### ISSUE TITLE
Visual confirmation that the Wake Up timer is set

### ISSUE THREAD

**Issue by brandonaut** [ashutoshgngwr/noice#502]
### Is your feature request related to a problem? Please describe.

When setting the Wake Up timer, I find it difficult to tell if the alarm is actually set or not. There's not a clear indication that it's enabled.

### Describe the solution you'd like

I really like how the native Android clock handles this. When you set the alarm time, it immediately shows a toast notification with the remaining time until the alarm goes off: "Alarm set for 3 hours from now". This has the added benefit of giving a sanity check that you set the alarm time properly, and didn't accidentally switch the AM/PM or something.

**Comment by ashutoshgngwr** [comment]
@brandonaut I just pushed a release and didn't notice this issue. I'll definitely add this in the next release.

**Comment by robercoding** [comment]
Do you mind if try to implement this solution? I'll add a UI test also 😄

**Comment by ashutoshgngwr** [comment]
@robercoding Sure, go ahead!
