### ISSUE TITLE
Share presets

### ISSUE THREAD

**Issue by nitrocode** [ashutoshgngwr/noice#503]
# Is your feature request related to a problem? Please describe.

My friend has a few presets set and to copy them I had to manually do it.

# Describe the solution you'd like

It would be nice to export and import presets so they can be shared

Love the app! Ty

**Comment by anarcat** [comment]
i would love to have that as well, i'd use it to share presets between my tablet and my phone, for example...

**Comment by Watson15683** [comment]
I would also appreciate to have a import/export feature. For my needs it would be enough to just be able to have some button to save the presets to a file, and a button to import that file again. So i can store and save my Presets in my Nextcloud.


### Optional
It would also be nice if the save file would be auto-updated every time i create a new preset.
(always with a new current date for the filename so the Nextcloudapp realizes that a new file has been created and auto uploads it) 
But i want to stress that the auto-update feature does not really add much value to the import/export feature, it would just be nice to have. Manual Backups would also do the Trick for me.

**Comment by franciscot** [comment]
@ashutoshgngwr: Can you save the XML presets file in /storage/Anddriod/data/ for example?  I could backup my presets or move/copy to another device.

**Comment by ashutoshgngwr** [comment]
> @ashutoshgngwr: Can you save the XML presets file in /storage/Anddriod/data/ for example?  I could backup my presets or move/copy to another device.

Seems unnecessary. The requested feature is more liberal – accessible to people without technical backgrounds. Will build integrations to import/export presets from the application itself.

**Comment by nsmirosh** [comment]
@ashutoshgngwr Is this feature request closed? Would love to help out on this feature :)

**Comment by ashutoshgngwr** [comment]
@nsmirosh No, this is still open. I am in the middle of refactoring the media playback service, so if you stay clear of that portion, it shouldn't be an issue. :+1: 

---
A few implementation details to consider:

- I was thinking of adding a _Preset_ category to the settings fragment for the import/export options.
- I was thinking of making the IO format a JSON object with the preference key and presets. e.g. the current version of presets is stored in a preference with key "presets.v1". Let's say if someone imports v1 presets in an app version that supports v2, we can implicitly perform data migration.
  For example, the output might look like:

  ```js
  {"version": "presets.v1", "presets": [...]}
  ```

  Migration related snippets:

  https://github.com/ashutoshgngwr/noice/blob/fc7a75ec786232d6573f19b19d5c2c482e1a21b4/app/src/main/java/com/github/ashutoshgngwr/noice/repository/PresetRepository.kt#L23-L30

  https://github.com/ashutoshgngwr/noice/blob/fc7a75ec786232d6573f19b19d5c2c482e1a21b4/app/src/main/java/com/github/ashutoshgngwr/noice/repository/PresetRepository.kt#L107-L172

Please let me know if you have any questions. I'd also love to hear your thoughts before you move onto the implementation if you don't mind.

**Comment by nsmirosh** [comment]
@ashutoshgngwr Sure, I'm new to the repo, so I'll make sure to review everything and discuss before I start with an implementation.

**Comment by ashutoshgngwr** [comment]
@nsmirosh I am preparing for the next release and I decided to closed this ticket. Please feel free to pick up anything else.
