### ISSUE TITLE
Text is cut off on small devices

### ISSUE THREAD

**Issue by MakiWolf** [ashutoshgngwr/noice#505]
### Description

Text is cut off on small devices in AppIntro.

### To Reproduce
Open menu and select help or by the first start of the app AppIntro starts by default.

### Screenshots

![grafik](https://user-images.githubusercontent.com/73300633/107865367-d210ca00-6e65-11eb-8916-2278f0dbbea0.png)
The last line in GERMAN TRANSLATION is cut off.

### Others
- Device: Sony Xperia XA AND Nexus 5 API 30 (from Android Studio Emulator)
- Android Version: 7
- App Version: 0.15.0

**Comment by ashutoshgngwr** [comment]
Nothing we can do on our end besides rephrasing the string to be shorter.  The app introduction is created using a third-party component (https://github.com/AppIntro/AppIntro).

**Comment by MakiWolf** [comment]
Thanks for answer, but I think making the string shorter does not solve the problem at all. Because there are also more smaller devices than the Sony Xperia XA. I just have set up a Nexus One API 30 in Android Studio Emulator and there is also in ENGLISH TRANSLATION, the last line cut off. I am quiet new to this AppIntro, but maybe there is a possiblity to make the text scrollable, where you can swipe up or down. I hope to find a solution for all smaller devices.
![grafik](https://user-images.githubusercontent.com/73300633/107876658-842cae00-6ec7-11eb-91a4-1ad29b9b87b4.png)

**Comment by ashutoshgngwr** [comment]
I guess we can make a custom layout fragment with the same layout but the icon should auto-adjust its dimensions (filling the space available on screen).

**Comment by robercoding** [comment]
Hey @ashutoshgngwr, I'd like to solve this issue :)!
