### ISSUE TITLE
Brown noise volume is too low

### ISSUE THREAD

**Issue by blackandyellowgecko** [ashutoshgngwr/noice#523]
### Is your feature request related to a problem? Please describe.
I need to slide the volume beyond the "safe volume" zone (that mark, with the red color, to tell the user that raising the volume that much might be dangerous to the ears) to hear brown noise better. After some time, the phone gets back to the volume to the "safe zone" mark and this is bad because brown noise is very good to sleep when you have tinnitus.

### Describe the solution you'd like
Improve the volume of brown noise.

**Comment by ashutoshgngwr** [comment]
@blackandyellowgecko Which app version are you currently using? 0.15.0 ships with slightly louder sounds.

**Comment by blackandyellowgecko** [comment]
Ops, sorry, I forgot to update this. I'm using 0.16.0 and it's louder. Thanks o/

**Comment by ashutoshgngwr** [comment]
Can I close this issue then? @blackandyellowgecko
