### ISSUE TITLE
Cast Integration (Chromecast) plays to one device in a Speaker Group pair

### ISSUE THREAD

**Issue by daetoCh0** [ashutoshgngwr/noice#539]
I have two Nest Minis in a speaker group. Noice's Cast feature only plays audio to one speaker in the group.

I'm filing as a bug because it looks like the project's MP3 assets are stereo-encoded, so it seems like this could be an issue with the Cast sender integration. Speaker groups are documented at the Google support link below:

https://support.google.com/googlenest/answer/7559493?co=GENIE.Platform%3DAndroid&hl=en-AU

**Comment by ashutoshgngwr** [comment]
This is most likely an issue on our side. I'll need to spend some time to investigate it further for certainty.

**Comment by ashutoshgngwr** [comment]
@daetoCh0 Sorry, but this is unlikely to get fixed. Google Developers portal is missing [documentation on Speaker Groups](https://developers.google.com/s/results/android?hl=en&q=speaker%20groups) altogether. In fact, it doesn't even mention such a thing.

Another person reported this very same issue (See #283), and they luckily found a workaround that worked for them.

**Comment by daetoCh0** [comment]
Thanks, @ashutoshgngwr. I'm looking thru the commits and it looks like some of your inspiration came from the AntennaPod project. I can give their app a try and see if the Speaker Group works.

In the other issue (#283) you asked:
> PS I was wondering when you used the Noice to cast audio, was it always the same speaker at fault or one of them would play randomly?

I can confirm that Noice will consistently cast to the primary device, which is the device that initiated the group.

**Comment by ashutoshgngwr** [comment]
@daetoCh0 While I remember mentions of the AntennaPod, Noice's implementation is uninfluenced by it. But sure, if AntennaPod works fluently, that will definitely give us a few clues about our shortcomings.

**Comment by daetoCh0** [comment]
OK, I'll check it out. Meanwhile, I'm pretty sure that the API calls this "multizone" or "multi-zone" rather than "speaker group."

https://developers.google.com/android/reference/com/google/android/gms/cast/CastDevice#CAPABILITY_MULTIZONE_GROUP

https://github.com/home-assistant/core/issues/39769

**Comment by ashutoshgngwr** [comment]
@daetoCh0 Nothing on Stackoverflow and nothing in the documentation. Please do let me know if you find anything else.
