### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [ashutoshgngwr/noice#54]
Hi @ashutoshgngwr 

I found this app: https://play.google.com/store/apps/details?id=cm.whitenoise.sound on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under MIT license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by ashutoshgngwr** [comment]
Thanks @Poussinou for the report! I've reported it to Google Play Support. Let's see what happens.

**Comment by ashutoshgngwr** [comment]
@Poussinou I heard back from Google Support. Looks like they aren't going to take any actions against it. I am closing this issue since there is nothing more to be done.

**Comment by yashpalgoyal1304** [comment]
The link is not working as of today. So that probably means that that app has been taken down. So, hooray!
