### ISSUE TITLE
Add dynamic app shortcuts for Presets

### ISSUE THREAD

**Issue by VasilisKos** [ashutoshgngwr/noice#579]
1. Add the option to locally backup presets.
2. Add app icon shortcuts of the presets, for instant playing.

**Comment by ashutoshgngwr** [comment]
@VasilisKos

>     1. Add the option to locally backup presets.

Will do it later.
 
>     2. Add app icon shortcuts of the presets, for instant playing.

It already exists. Go to the preset list, click on the drop-down button, and select "Add to home screen". Please let me know if it is what you were looking for.

**Comment by VasilisKos** [comment]
No. I'm talking about the app icon shortcuts. The ones that appear when you long tap the app icon.

**Comment by ashutoshgngwr** [comment]
@VasilisKos Alright I will look into that as well.
