### ISSUE TITLE
Desktop App

### ISSUE THREAD

**Issue by trymeouteh** [ashutoshgngwr/noice#598]
Please consider making a desktop version of this app which can be minimised to the tray for Windows, Mac and Linux.

**Comment by ashutoshgngwr** [comment]
@trymeouteh This is a native Android app and would need a complete rewrite using different technologies to be able to do that. I am closing this as this is out of scope here.

**Comment by ashutoshgngwr** [comment]
Hey @trymeouteh! An early prototype of a web application for Noice is now available at https://app.trynoice.com. The source code is available at https://github.com/trynoice/web-app-v0.
