### ISSUE TITLE
Group options into a dedicated settings page to clean up menus

### ISSUE THREAD

**Issue by Lurux** [ashutoshgngwr/noice#602]
### Is your feature request related to a problem? Please describe.
It's not really a problem, but I think it might help the UI feel a bit more streamlined.

### Describe the solution you'd like
I think the various options spread out across different screens could be consolidated into a dedicated settings page, containing:

- Theme
- Page shown at startup
- Wakeup timer options

![settings](https://user-images.githubusercontent.com/35870988/115908966-2094a300-a46b-11eb-8f1d-333bddca9974.png)

Do note this doesn't prevent us to keep the options concise and simple !

In order to improve discoverability, a discrete "settings" button could be added in the bottom-right corner of the presets and timer pages, highlighting the corresponding settings section.

Btw, I think the same should be applied to all the help and support links currently residing in the menu:

![menu](https://user-images.githubusercontent.com/35870988/115909409-c8aa6c00-a46b-11eb-9557-d7dbac45f418.png)

I almost forgot: **Thanks for this amazing app !**

**Comment by ashutoshgngwr** [comment]
Coincidence? I think not! :laughing: 

![2021-04-23_23-20](https://user-images.githubusercontent.com/7106123/115910603-a70cad00-a48a-11eb-9e81-12c3c8bcdecb.png)

**Comment by Lurux** [comment]
Wow, nice ! Has the update been released yet ? (I'm using the f-droid version, so I assume it may take a little longer to reach me).

Will this include a decluttered menu too, as my second image suggests ?

**Comment by ashutoshgngwr** [comment]
@Lurux Nope, it's still in works.

Maybe. Will work on the menu. Won't be exactly as you suggested.

**Comment by Lurux** [comment]
Ok, thanks !
