### ISSUE TITLE
Launcher supports shortcuts but app errors with "Your default launcher does not support adding shortcuts"

### ISSUE THREAD

**Issue by sudomain** [ashutoshgngwr/noice#606]
### Description

My launcher supports shortcuts but Noice  gives the error `Your default launcher does not support adding shortcuts`. The launcher in question is [Rootless Pixel Launcher](https://f-droid.org/packages/amirz.rootless.nexuslauncher) which supports Android  shortcuts and widgets.
### To Reproduce

1. Use Rootless Pixel Launcher
2. in Noise, go to saved presets and try to add a shortcut to the homescreen
3. Get `"Your default launcher does not support adding shortcuts"`. Note that I can only see this error when the phone is in landscape orientation: If it's in portrait mode I only see part of the message as it's cutoff by the text `"show saved presets on app startup"`, but this is a separate issue.
### Others
- Device:  LGL84VL
- Android Version:  7.0
- App Version:  0.16.0 (F-Droid)

I have no attachment to this particular launcher and I can switch to an alternative that fills these needs:
1. On Fdroid
2. Supports shortcuts and widgets

**Comment by ashutoshgngwr** [comment]
Are you able to create app shortcuts using other apps? I tried to reproduce it, but unfortunately, I couldn't.

https://user-images.githubusercontent.com/7106123/116029904-f6fc9700-a677-11eb-84b0-43e0c541802a.mp4

**Comment by sudomain** [comment]
Yup. There are shortcuts and widgets that can be added by long-pressing a blank area on the home screen. Termux is an app that had one of each. There's also shortcuts that can only be added from within the app which it seems is the kind Noice uses. Firefox has one of these (hamburger menu > add to homescreen) which also works with this launcher.

**Comment by ashutoshgngwr** [comment]
Can you examine the installed APK on your device and see if it has `com.android.launcher.permission.INSTALL_SHORTCUT` permission? Noice uses Jetpack compact API to create shortcuts. Other than missing permission, I can't see any reasons why it shouldn't be able to add shortcuts.

**Comment by sudomain** [comment]
Yup, that perm isn't listed.

**Comment by sudomain** [comment]
I got the update from FDroid and now shortcuts show up on the homescreen. When I try to play one of these shortcuts though it gives me a toast saying "App isn't installed". This may be an issue with this launcher though
