### ISSUE TITLE
Feature request: respond to KEYCODE_MEDIA* media buttons

### ISSUE THREAD

**Issue by sudomain** [ashutoshgngwr/noice#607]
### Is your feature request related to a problem? Please describe.

Please have the app respond to media buttons such as 
`KEYCODE_MEDIA_STOP`, `KEYCODE_MEDIA_PLAY`, and `KEYCODE_MEDIA_PLAY_PAUSE` so that sounds can be affected by hardware media buttons.
https://developer.android.com/guide/topics/media-apps/mediabuttons

### Describe the solution you'd like

Play, pause, stop, and play/pause toggle via media buttons please. Another idea could be `KEYCODE_MEDIA_NEXT` and `KEYCODE_MEDIA_PREVIOUS` to cycle through the saved presets.

**Comment by ashutoshgngwr** [comment]
And you'd think that media session callback will handle that for you. I am really starting to hate how Android is turning out to be lately.

**Comment by sudomain** [comment]
Thank you for the quick response on this and the other issue. What is your opinion on KEYCODE_MEDIA_NEXT and KEYCODE_MEDIA_PREVIOUS to cycle through the saved presets?

**Comment by ashutoshgngwr** [comment]
@sudomain I'll be working on that among other things. I was going to add media player style notifications, but that requires some code restructuring before implementation. These media buttons should be partially implemented during the notification implementation. Nevertheless, it'll all be available in the next release.
