### ISSUE TITLE
Dual Samples

### ISSUE THREAD

**Issue by crogonint** [ashutoshgngwr/noice#62]
Some of the included samples are terribly irritating. An example is the Bonfire sample. It's about 1 1/2 seconds long, and for all the world sounds like somebody left a record player on after the record was finished.

Sounds which by nature will have a repetitive pattern like this one are easily masked, however. You simply have two separate samples of different lengths. For example, for this bonfire, I would recommend two samples, one eight seconds long, and one 15 seconds long. If you start them both at the same time, and repeat them both (assuming a smooth transition on both samples, of course), it would be several minutes before the pattern repeats.

Both samples should be of equal volume, and could both be controlled by the same volume selector. This functionality is simply to provide a non repetative sample, it's not necessary to have it appear as two separate samples. ;)

**Comment by ashutoshgngwr** [comment]
That's a neat idea. I want to give it a try for sure but I am finding it difficult to manage time to work on hobby projects these days. In the meantime, if you can take this up and ahead, I'll be happy to help. If not, I'll try to work on it but I can't promise anything. :sweat_smile:

**Comment by crogonint** [comment]
I've probably got some free to use sound samples already downloaded somewhere, from soundbible.com or one of the other ones from back in the day.

I don't do much programming these days though. I can pair up some samples, and make sure that fade cleanly, but you'll have to hammer it in to the code. ;)

**Comment by ashutoshgngwr** [comment]
@crogonint awesome. Please do that!

**Comment by ashutoshgngwr** [comment]
@crogonint Whenever you can, send me the samples before due date of the milestone. I want to add better audio samples to next version.

**Comment by dector** [comment]
@crogonint can you share examples in this issue please?

**Comment by crogonint** [comment]
I haven't forgotten about you guys, I've just gotten terribly busy. I'm
currently installing some multimedia and audio apps. Give me a few days and
I should be set up to put a few samples together. :)

**Comment by crogonint** [comment]
Just an FYI, I didn't forget about this, my sound samples are on a random drive that I haven't located yet. I'll be going through the drives today. Cross your fingers...

**Comment by crogonint** [comment]
@ashutoshgngwr 

I was pretty happy with most of the samples already in use.

What bit rate would you like use as an HD standard?

**Comment by ashutoshgngwr** [comment]
@crogonint with current standard 128-192 kbps is what I considering the best quality for sounds. Of course this after taking app size into consideration.

**Comment by crogonint** [comment]
Yeah I don't think that 128kbps is totally necessary for most of these, I mean they're mostly ambient. I could maybe see birds, or people mumbling, or thunder.. Sounds that actually benefit from a higher sound density..

Tell you what, I use a lot of RPG sound thingies, I'll see what they're using as a standard for background noises and sounds.

**Comment by crogonint** [comment]
Just an update, I finally located my massive library of sample sounds! Woo-hoo!! Just want to let you know I didn't forgt, I'll get this back around on the front burner sooner or later. Actually, if you're moving to hi-fidelity sounds, I'll have to double check the sample rates on my end. I use this stuff for sound effects mainly, so I'm not always very picky about getting the best sample rate. ;)

**Comment by ashutoshgngwr** [comment]
@crogonint This is done, closed and released. Thanks for your input!

**Comment by crogonint** [comment]
Congrats! I haven't seen an update come through lately, I'll check and see why I missed it. :)
