### ISSUE TITLE
Put a volume slider in the saved presets screen

### ISSUE THREAD

**Issue by blackandyellowgecko** [ashutoshgngwr/noice#621]
### Is your feature request related to a problem? Please describe.
Currently, there's no volume slider in the saved presets screen:
![Screenshot_20210430-033146](https://user-images.githubusercontent.com/78433932/116657345-9fef0e80-a964-11eb-8193-3df7eef4fe3d.png)

### Describe the solution you'd like
Add a volume slider for each item in the saved presets screen.

**Comment by ashutoshgngwr** [comment]
Does your device not have volume buttons?

**Comment by blackandyellowgecko** [comment]
> Does your device not have volume buttons?

In the library screen, there's a volume slider for each item, maybe the saved screen presets could have it

**Comment by ashutoshgngwr** [comment]
@blackandyellowgecko At any given time, only one preset can play. The slider would be doing exactly what volume buttons do, which is not the case with sounds in the library.

**Comment by ashutoshgngwr** [comment]
I am closing this. It doesn't make any sense. Please let me know if you think otherwise.

**Comment by bqv** [comment]
It does make sense. E.g. I use noise apps as background while listening to podcasts. It'd be nice to be able to turn down the noise so i can actually hear speech, like any other noise app, without having to manually scale each individual sound and possibly mess up ratios.

**Comment by ashutoshgngwr** [comment]
That sounds like a very specific use case and I don't think it's a good idea to add complexity to include every possible scenario. If you want to listen to podcasts, create and save a preset with low volume settings.
