### ISSUE TITLE
App presets shortcuts icons

### ISSUE THREAD

**Issue by VasilisKos** [ashutoshgngwr/noice#637]
### Description
Only one of the created app presets shortcuts has the proper icon.

### To Reproduce
1. Add a preset to app shortcuts. The shortcut has the proper "play" icon.
2. Add other presets. They have the generic Android icon.

### Screenshots
![Screenshot_20210506-234035](https://user-images.githubusercontent.com/12777771/117365180-949d6500-aec7-11eb-851f-a50008ec521a.png)

### Others
- Device: Nokia 6.2
- Android Version: 10
- App Version: 0.17.0 (Play)

**Comment by ashutoshgngwr** [comment]
It is either an upstream bug or a limitation. I tested different things extensively while implementing this, and it seems like the Android API doesn't allow using the same icon for multiple app shortcuts. There is no documentation about this, so we can't really be sure.

https://github.com/ashutoshgngwr/noice/blob/2d5b682fb87b549f71b0e7efd19a35e188fbde0c/app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetFragment.kt#L194-L208

**Comment by VasilisKos** [comment]
Looks like you're right, as almost all of my apps shortcuts use different icons, EXCEPT Solid Explorer. It has the same folder icon for all bookmarked folders. So, I guess there's a workaround and probably no API limitation. 

![Screenshot_20210507-104321](https://user-images.githubusercontent.com/12777771/117415527-17064300-af21-11eb-9bee-a38e3f169a85.png)

**Comment by ashutoshgngwr** [comment]
@VasilisKos Will try to find the workaround.

**Comment by ashutoshgngwr** [comment]
[I give up!](https://stackoverflow.com/questions/67434914/icon-is-not-visible-when-used-with-two-or-more-dynamic-shortcuts-simultaneously)

**Comment by ashutoshgngwr** [comment]
![image](https://user-images.githubusercontent.com/7106123/131240691-8862327f-398e-40ae-8919-421c5107ad30.png)

I just ran the latest version on the Android 9 emulator and it works. Is it working for you as well @VasilisKos?

**Comment by VasilisKos** [comment]
Yeap! Works fine on Android 10! Thanks a lot! 👍

**Comment by ashutoshgngwr** [comment]
@VasilisKos I didn't do anything. It was an upstream bug.
