### ISSUE TITLE
text overflow issue in list of sounds

### ISSUE THREAD

**Issue by Watson15683** [ashutoshgngwr/noice#638]
### Description
For the German taranslations the text sometimes clips into the Images (like shown in the image below). It looks a bit weird. IMO the text cannot be rephrased (English ==> German) into a shorter format, without loss of information. So some kind of line break seems appropriate. 

### Screenshots
![Screenshot_20210507-214154_Noice](https://user-images.githubusercontent.com/79628154/117501516-6dee3580-af7e-11eb-9722-6effdefd64a5.png)

### Others
0.17.0 beta

**Comment by ashutoshgngwr** [comment]
That's by design. The images are supposed to be in background.

**Comment by Watson15683** [comment]
Ok, i can see how that could work :-) 
I think that the overlap does affect the "readability" of the Text and the Image negatively, due to the lower contrast and the overlapping of the two different geometries. 
And for German translations there is **only one** Sound that has this overlap, which makes this sound stick out in a odd way. And so it may not seem intentional at least for German app users. I did not check other languages. 

### On the Solution

A simple 2 Boxes Model would not suffice, because the flow into the Box of the Images may look good for other sounds. Like in the example below.
![Screenshot_20210508-105710_Noice](https://user-images.githubusercontent.com/79628154/117533408-facfd800-afec-11eb-96ce-a3250ea9622b.jpg)

The optimal way would be to add a line break as soon as the Black colour of the Text overlaps with the grey of the Images.

I'd like to hear what you think about this ;-)

**Comment by ashutoshgngwr** [comment]
There's no magic method available to add a line break when the text overlaps the darl background. It either wraps around the image (rectangle) or hovers over it. I certainly am not going to put effort in coming up with a solution for this.

Maybe we can further dim down the icons or something.

**Comment by Watson15683** [comment]
Am sorry i have absolutely no clue about what is possible and what isn't.
I made the two examples with the rectangle model and a think they both look very nice. So in Conclusion IMO the Rectangle Model would be a good improvement of the UI.

![Screenshot_20210508-172136_Noice](https://user-images.githubusercontent.com/79628154/117544603-87e15400-b022-11eb-81bc-3b4959dd6493.jpg)
![Screenshot_20210508-1721306_Noice](https://user-images.githubusercontent.com/79628154/117544604-8879ea80-b022-11eb-9117-50feca4091e7.jpg)
