### ISSUE TITLE
Frequency setting does nothing

### ISSUE THREAD

**Issue by stemy2** [ashutoshgngwr/noice#650]
### Description
No matter how much time i set to the frequency setting, the concerned sound doesn't repeat at all.

### To Reproduce
1. Set the frequecy setting to a random number
2. The concerned sound doesn't repeat at the expected rate (actually doesn't repeat at all).

### Others
- Device: Samsung Galaxy S7
- Android Version: 8.1
- App Version: 0.17

**Comment by ashutoshgngwr** [comment]
Unable to reproduce. I did the following

1. Play howling wolf
2. Set repeat interval to 1 min.
3. Sound repeats at a random interval in range 0-60 seconds.

Are you able to play multiple looping sounds without any issues? It might be possible that the device is running out of memory.

**Comment by stemy2** [comment]
I did almost the same


1.     Play howling wolf
2.     Set repeat interval to 30 sec.
3.     Waited 30 second without hearing the sound again

I can hear multiple loop sound and my phone is not out of memory.

**Comment by ashutoshgngwr** [comment]
I am not able to reproduce this on Xiaomi Mi A3 (Android 11) and Emulator (Android 9). Please try to reproduce the issue on a different device.

**Comment by ashutoshgngwr** [comment]
Feel free to re-open this issue if anything changes.
