### ISSUE TITLE
'App isn't installed' error on playing a preset using home screen shortcuts

### ISSUE THREAD

**Issue by ashutoshgngwr** [ashutoshgngwr/noice#651]
I got the update from FDroid and now shortcuts show up on the homescreen. When I try to play one of these shortcuts though it gives me a toast saying "App isn't installed". This may be an issue with this launcher though

_Originally posted by @sudomain in https://github.com/ashutoshgngwr/noice/issues/606#issuecomment-840439108_

**Comment by ashutoshgngwr** [comment]
@sudomain I am able to reproduce on an emulator device (Android 5.1). Will fix it ASAP.

**Comment by sudomain** [comment]
Thanks!
