### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by dasnessie** [ashutoshgngwr/noice#66]
### Is your feature request related to a problem? Please describe.
I sometimes like to use the app as background sound when I can't fall asleep. However, I do not want the app to run all night.

### Describe the solution you'd like
I would really love an option to stop the sound after a period of time I can define, probably somewhere between ten minutes and two hours.

**Comment by ashutoshgngwr** [comment]
Noted!

**Comment by dector** [comment]
+1 for this. Extremely handy feature if one is using the app before going to sleep.

Thanks for the app, btw!
