### ISSUE TITLE
Noice plays multiple random sounds when pressing "Previous/Next track"

### ISSUE THREAD

**Issue by Long-FA** [ashutoshgngwr/noice#683]
### Description
On newer versions of Android, when using Noice or any music playing app, a sticky notification will appear on Quick Settings, allow you to return to previous track, play/pause or move to next track with the help of three buttons :previous_track_button:  :play_or_pause_button: :next_track_button: . When pressing either Previous Track or Next track, Noice will play multiple random sounds together, at random volumes. I don't know if this is an intended behavior or not, but it is certainly not helpful.

### To Reproduce
1. Open Noice and play one sound.
2. Pull down the notification area on top of Android
3. Press either the :previous_track_button:  or :next_track_button: icon.

### Others
- Android Version: 11
- App Version: 0.17.0 (F-Droid)

**Comment by ashutoshgngwr** [comment]
@Long-FA It is intended behaviour. When a saved preset is playing, these buttons loop through all saved presets. When an unsaved preset is playing, these buttons generate random mixes on the fly.

An alternative could be to add a setting to disable it for unsaved presets. Would that work?

**Comment by Long-FA** [comment]
Thank you, that would be helpful. I use Noice to help falling into sleep, and it is very problematic when i accidentally press Previous/Next track on my IEM and have a seagull screamed into my ears.

-------- Original Message --------
