### ISSUE TITLE
Question about the analytics

### ISSUE THREAD

**Issue by opk12** [ashutoshgngwr/noice#728]
### Description
Does the f-droid build do data collection by default, or without prior explicit user consent? If so, it should be marked with [the Tracking antifeature](https://f-droid.org/docs/Anti-Features/#Tracking) which it currently does not have

**Comment by ashutoshgngwr** [comment]
@opk12 F-Droid build doesn't have analytics. Only the Play Store build has the capability to collect analytics data.

**Comment by NSTAdventure** [comment]
Bruh 🗿
