### ISSUE TITLE
Fdroid still suffers from build queue delays

### ISSUE THREAD

**Issue by rancidfrog** [ashutoshgngwr/noice#732]
On fdroid: "_Version 1.0.2 (43) suggested Added on 2021-07-26_ "
Having APKs on release section would be great.
Reproducible builds, which supposedly solves signing issues

**Comment by ashutoshgngwr** [comment]
Signing issues will persist because I have opted in for Google Play App signing and F-Droid does their own thing. But, I'll try to add APK release artifacts in the GitHub actions workflow.

**Comment by ashutoshgngwr** [comment]
It's done. If everything works as expected, APKs should appear in the latest release once the Android workflow passes. https://github.com/ashutoshgngwr/noice/actions/runs/1085515170

**Comment by rancidfrog** [comment]
Thank you,
That was quick.
