### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by NSTAdventure** [ashutoshgngwr/noice#751]
### Is your feature request related to a problem? Please describe.
No animation :( not too relaxing

### Describe the solution you'd like

Add animation when playing sound especially using preset

**Comment by ashutoshgngwr** [comment]
The purpose of Noice is to provide a constant background noise while you do something else (besides staring at the UI of Noice). Thus, this feature is unnecessary. Perhaps I am wrong since the description is too vague.

**Comment by NSTAdventure** [comment]
> The purpose of Noice is to provide a constant background noise while you do something else (besides staring at the UI of Noice). Thus, this feature is unnecessary. Perhaps I am wrong since the description is too vague.

Yeah i also have English grammar issues wait 🗿🤦

**Comment by ashutoshgngwr** [comment]
Yeah, you get it.

**Comment by ashutoshgngwr** [comment]
Yeah, you get it. ¯\\\_(ツ)\_/¯

**Comment by NSTAdventure** [comment]
> Yeah, you get it. ¯\_(ツ)_/¯

Finally bro pls check again and consider to re open my issues thanks 🙏😊
