### ISSUE TITLE
add option not to move playing sounds to the top

### ISSUE THREAD

**Issue by rubo77** [ashutoshgngwr/noice#77]
### Is your feature request related to a problem?
When listening to all the sounds in the library one after another, sometimes it would be handy if you wouldn't have  to scroll to the top to stop the sound again

### Describe the solution you'd like

Please add an option to turn off this behaviour

**Comment by ashutoshgngwr** [comment]
@rubo77 I have planned a major refactor for Noice but I am not able to find the time lately. I was thinking of removing the feature altogether but I think adding an option sounds even better.

If you want to track progress (which is tending to 0 right now) on the refactor, see #68

**Comment by ashutoshgngwr** [comment]
This feature has been removed in #68
Closing!
