### ISSUE TITLE
Give the user the ability to assign menu items to the bottom menu bar

### ISSUE THREAD

**Issue by aproposnix** [ashutoshgngwr/noice#778]
## Background 
Recently the menu layout changed. I have found it very frustrating because it changed how I interact with the app. One of the things that bothers me is that there is no visual clue (useful when you don't have your glasses on) for the sleep timer which I use every day. I think this proposal would resolve that issue for me. 

## Proposal

It would be nice to be able to assign menu items to the menu bar at the bottom of the app. Currently you have three predefined options:

* Library 
* Saved Presets
* Wake-up Time 

I would like to be able to remap those three to whatever menu items I want. In my case, I *never* use Wake-up timer but I use the sleep timer every night.

**Comment by ashutoshgngwr** [comment]
https://github.com/ashutoshgngwr/noice/commit/575cefceb24114e662ddb11c1d583604893ff65b is a temporary fix until #542 is implemented.
