### ISSUE TITLE
Cannot reset sleep timer

### ISSUE THREAD

**Issue by rkyoku** [ashutoshgngwr/noice#779]
### Description

The timer duration is anormaly huge (35 hours, I did not extend it myself) and also clicking on the reset button has no effect (even after an app update and a phone reboot).
I am stuck.

### To Reproduce

No idea, it appeared by itself without human intervention

### Screenshots

![Screenshot_20210828-002023](https://user-images.githubusercontent.com/676896/131194207-df217e49-3275-472d-9ff2-d6a1f961d0d4.jpg)

### Others
- Device:  OnePlus 8T
- Android Version:  OxygenOS 11.0.10.10
- App Version:  1.2.1 F-Droid

**Comment by ashutoshgngwr** [comment]
Export your saved presets and then Force close Noice and clear its data. Noice saves the timer state on the storage which it supposedly failed to invalidate when the timer was reset.

**Comment by ashutoshgngwr** [comment]
Unrelated, but there was actually a bug that kept the "reset" button disabled on opening the sleep timer screen when a timer was ongoing. While your issue seems independent of this bug, the reset button will now be enabled should it happen again.
