### ISSUE TITLE
Device sometimes freezes on overnight usage

### ISSUE THREAD

**Issue by jeisinge** [ashutoshgngwr/noice#781]
### Description
I have been running Lineage OS 18.1 on my Pixel 2 XL for about a 40 days. I have run Noice at night and five times. The phone has locked twice in those 40 days - both times when Noice has been running at night. So, be I believe Noice might be the cause.

The first time, I woke to the phone locked up and very hot - I don't remember which screen it was on.

The second time, the phone was just locked on the locked screen.  The second time, the version was 1.2.1. The phone locked about 45 minutes after placing it down for the night.

If there are logs I can grab from last night's crash, let me know and I can grab them for you!

### To Reproduce
I cannot reproduce consistently. However, I do know I started Noice and continued to use my phone and light for about thirty minutes before putting the phone down. The phone is hooked up to a charger.

### Others
- Pixel 2 XL
- Lineage OS 18.1

**Comment by ashutoshgngwr** [comment]
I am sorry, but I need more clarification. What do you mean when you say that you wake up to a locked phone? I am assuming this is different from a normal screen lock?

**Comment by jeisinge** [comment]
The phone is completely frozen/crashed. The screen is on with a time from when it crashed. The phone doesn't respond to any touch or button presses. No sound. Complete crash.

**Comment by ashutoshgngwr** [comment]
Noice doesn't perform any resource-intensive operations besides loading the currently playing sounds into device memory. The sounds themselves are comparatively small (should be about 5 MBs each after decoding to raw PCM). You can check Noice's memory usage and see if it's disproportionate. Other than that, it's unlikely that Noice is at the bottom of this.  I can't think of anything else in Noice that has the potential to freeze the entire operating system.

**Comment by bqv** [comment]
It does seem rather resource intensive actually. Playing noice and a podcast simultaneously basically grinds my phone to a halt. No other noise app does this

**Comment by jeisinge** [comment]
After reinstalling from the Play Store, I no longer have this issue. But sometimes the sound doesn't last the entire night.

**Comment by ashutoshgngwr** [comment]
> After reinstalling from the Play Store, I no longer have this issue. But sometimes the sound doesn't last the entire night.

@jeisinge This could be battery optimization. See #220 to turn it off!

**Comment by ashutoshgngwr** [comment]
> It does seem rather resource intensive actually. Playing noice and a podcast simultaneously basically grinds my phone to a halt. No other noise app does this

@bqv 

I profiled Noice's resource usage. The following are some key stats:

1. On playing all 35 sounds together: CPU usage: 51% peak, RAM Usage: 301 MBs peak
2. On playing 10 random sounds: CPU Usage: 16% peak, RAM Usage: 197 MBs peak

This was a debug build on an idle device. In real scenarios, a lot of apps could be running in parallel. These stats could be better, but they aren't bad either. From my personal experience, I don't think I've ever played more than 6 sounds at once on prolonged use.
