### ISSUE TITLE
Editing presets

### ISSUE THREAD

**Issue by VasilisKos** [ashutoshgngwr/noice#793]
It'd be very convenient to be able to edit presets. This could be done by:
1. Add an "Edit" option in the three doors menu of each preset.
2. While a preset is played, and you go to the sounds tab and edit the played sound, tapping the save button should pop-up a menu, asking whether to overwrite the currently played preset or save it as a new one. Like "Overwrite current preset?", with "Yes"  or "No" options. Tapping "No" should show the common "Save preset" window, that asks for a name for it.

**Comment by ashutoshgngwr** [comment]
Duplicate https://github.com/ashutoshgngwr/noice/issues/328
