### ISSUE TITLE
Setting to disable earphone controls

### ISSUE THREAD

**Issue by mobilefrog** [ashutoshgngwr/noice#800]
When using wired headphones for sleeping the pause controls can accidentally be pressed when rolling over resulting in waking up.

A setting to disable this function would make this app the perfect sleep app.

**Comment by ashutoshgngwr** [comment]
Already resolved in commit https://github.com/ashutoshgngwr/noice/commit/de7940882744b6bf3b318700fac838f2289cfd14. It should be available in the next release.
