### ISSUE TITLE
The website uses a mockup of iPhone X, but the app is only available for Android

### ISSUE THREAD

**Issue by flexagoon** [ashutoshgngwr/noice#810]
That's probably a bit misleading, maybe you should change it to something like OnePlus or Google Pixel

**Comment by ashutoshgngwr** [comment]
The website uses a pre-designed Jekyll theme ([automatic-app-landing-page](https://github.com/ashutoshgngwr/automatic-app-landing-page)) for the landing page. I made a few changes to the original theme to make it more Android-y but didn't notice the device frame. Anyways, we'll be moving away from Jekyll in the upcoming releases and the look and feel are bound to change with that.

**Comment by flexagoon** [comment]
The issue is still not resolved, Jekyll is still used.

**Comment by ashutoshgngwr** [comment]
@flexagoon Noice now has a new homepage. https://trynoice.com
