### ISSUE TITLE
Add sound of crashing waves

### ISSUE THREAD

**Issue by PanderMusubi** [ashutoshgngwr/noice#813]
### Is your feature request related to a problem? Please describe.
Add sound of crashing waves as was discussed in https://github.com/ashutoshgngwr/noice/issues/534#issuecomment-822836768

### Describe the solution you'd like
Add waves from https://freesound.org/people/Luftrum/sounds/48412/ (after converting to MP3).

This is also used in `waves.ogg` in https://github.com/rafaelmardojai/blanket/tree/master/data/resources/sounds

Possibly add more sounds used in Blanket when relevant, see https://github.com/rafaelmardojai/blanket/blob/master/SOUNDS_LICENSING.md for sources and licences.

**Comment by ashutoshgngwr** [comment]
@PanderMusubi current we're using [this](https://github.com/ashutoshgngwr/noice/raw/main/app/src/main/assets/seaside.mp3) \[[original source](https://sound-effects.bbcrewind.co.uk/search?q=07044050)\]; it is titled "Seaside" in the app. I don't think these sound effects are different, are they?
