### ISSUE TITLE
Help: How to send intent to start a preset

### ISSUE THREAD

**Issue by pjones** [ashutoshgngwr/noice#907]
First off, thank you so much for Noice!

I'm trying to automate my use of Noice by sending an intent via Tasker.  The overall gist of the automation is to connect to a set of bluetooth speakers, set the volume, then start a Noice preset.  It's the latter part that I can't seem to get working.

From what I can tell, Noice listens for a `play_preset` intent action and uses the `preset_id` extra intent item to play the specified preset.  However, I'm a bit out of my depth and so I can't figure out:

  1. How to construct the full intent to send to Noice.  Is `android.intent.action.play_preset` correct?
  2. How to discover the ID for a preset.  So far I created a launcher shortcut and then, using a backup of my launcher's settings, extracted the shortcut ID.  Would that be the same as the preset ID?
  3. How to send the preset ID with the intent?  Do I just send `preset_id:<ID>` in the Tasker [extras field](https://tasker.joaoapps.com/userguide/en/intents.html)?

Any help would be greatly appreciated.  Thank you.

**Comment by ashutoshgngwr** [comment]
Hey @pjones 

You're slightly off the track. Noice uses most intent internally to deliver control events to the player process. It effectively means that it cannot receive these intents from other apps. As per your requirements, there are two external intents that Noice listens.

1. In [ShortcutHandlerActivity](https://github.com/ashutoshgngwr/noice/blob/main/app/src/main/java/com/github/ashutoshgngwr/noice/activity/ShortcutHandlerActivity.kt): When you start a preset using a home screen shortcut. The following shortcut is how its intent is created. Only `EXTRA_PRESET_ID` is the required param.

   https://github.com/ashutoshgngwr/noice/blob/c9be9cc94328d6ebbc12a53a23b657fb4fc4a1ef/app/src/main/java/com/github/ashutoshgngwr/noice/fragment/PresetsFragment.kt#L221-L227

2. Using Preset URIs: When you share presets, Noice encodes them to HTTP URLs. You can simply send `android.intent.action.VIEW` with its data URI set to the one you obtained from Noice. To obtain a preset's URL, go to 'saved presets', open an item's drop-down context menu and click on share. These URLs are self-sufficient, i.e. they don't need internet.

To obtain preset ids, you'll have to examine the app's shared preferences and look for [UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format). I'll advise against it as these are Noice's private APIs and can change unexpectedly in the future.

I hope this answers all of your questions. If not, please feel free to re-open this issue.

**Comment by pjones** [comment]
That worked perfectly.  Thanks!
