### ISSUE TITLE
Can you add Pomodoro Timer Feature…?

### ISSUE THREAD

**Issue by Nimendra11** [ashutoshgngwr/noice#912]
## Can you add pomodoro timer like this 👇👇

 1.end of pomodoro session noice app says,  
            hii buddy, pomodoro session is over. Take a little break.(pausing playing noises)
 2.and end of break noice app says,
            buddy, our break is over, let's go back to work. (starting playing noises)

**Comment by ashutoshgngwr** [comment]
I will look into it post v2 release. Right now, all efforts are directed at finishing the v2 implementation.

**Comment by ashutoshgngwr** [comment]
just noticed that it is duplicate of #443
