### ISSUE TITLE
[question] library via internet

### ISSUE THREAD

**Issue by DC7IA** [ashutoshgngwr/noice#924]
The announcement vor v2 containes this:

> `o remove these constraints, we’ll start serving the library over the internet.

Does this mean I will not be able to use the app without internet connection?

**Comment by ashutoshgngwr** [comment]
I am still working on it and its a long way from being done. So far, I am planning to make offline playback a paid feature. But, streams on free/no accounts would still be cached on device, so while it would need an active connection for cache validation, it shouldn't generally use more data (for streaming more than once).

If you have privacy concerns related to online streaming, please note that
1. Noice currently collects analytical data about playback when downloaded from Play Store.
2. The Android app is and will remain open-source to maintain transparency. The only (future) closed sourced portions are the sound streams and basic account/subscription data management logic (on a remote server).
3. I have tried to follow GDPR guidelines related to data collection where no user data is ever transmitted without the explicit consent of the user. However, it may be stored offline (on user's device) and transmitted later when they allow Noice to do so.

I hope that addresses all of your concerns. Feel free to re-open the issue if you need more information.

**Comment by DC7IA** [comment]
Oh, that's sad. :/

To me the best feaute was always having some calming sound even when there was no internet connection.

Guess I'll have to stick with the old version then.

Thanks!

**Comment by DC7IA** [comment]
My suggestion would be to keep the current sounds, but add the new sounds online.

That  way there's always something to play without an internet connection.

**Comment by ashutoshgngwr** [comment]
Noted!
