### ISSUE TITLE
Sound Licenses

### ISSUE THREAD

**Issue by onkoe** [ashutoshgngwr/noice#945]
Hello,

Are the sound licenses noted anywhere? I would like to use these in my project but didn't see individual licenses. Are they actually licensed under the GPL???

Many thanks,
Barrett

**Comment by ashutoshgngwr** [comment]
You can take the sounds from their [original sources](https://ashutosh.blog/noice/contributors#sounds). The edited ones in this project are additionally covered by GPL.
